-- Run as the application schema owner. This script can be run again safely.

WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
WHENEVER OSERROR EXIT FAILURE

SET DEFINE OFF;
SET SERVEROUTPUT ON;
SET VERIFY OFF;

PROMPT Step 003 - survey-design tables started.

DECLARE
    PROCEDURE create_table_if_missing(p_table_name VARCHAR2, p_sql CLOB) IS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_count
        FROM user_tables
        WHERE table_name = UPPER(p_table_name);

        IF v_count = 0 THEN
            EXECUTE IMMEDIATE p_sql;
            DBMS_OUTPUT.PUT_LINE('created table ' || p_table_name);
        END IF;
    END;
BEGIN
    create_table_if_missing('HGB_SURVEY_TEMPLATES', q'[
        CREATE TABLE HGB_SURVEY_TEMPLATES (
            SURVEY_TEMPLATE_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            TEMPLATE_CODE VARCHAR2(80) UNIQUE NOT NULL,
            TEMPLATE_NAME NVARCHAR2(200) NOT NULL,
            DESCRIPTION NVARCHAR2(1000),
            STATUS VARCHAR2(20) DEFAULT 'ACTIVE',
            CREATED_BY_USER_ID NUMBER,
            CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
        )]');

    create_table_if_missing('HGB_SURVEY_TEMPLATE_VERSIONS', q'[
        CREATE TABLE HGB_SURVEY_TEMPLATE_VERSIONS (
            TEMPLATE_VERSION_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            SURVEY_TEMPLATE_ID NUMBER NOT NULL,
            VERSION_NO NUMBER NOT NULL,
            VERSION_LABEL VARCHAR2(50),
            STATUS VARCHAR2(20) DEFAULT 'DRAFT',
            PUBLISHED_AT TIMESTAMP,
            CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
        )]');

    create_table_if_missing('HGB_SURVEY_QUESTIONS', q'[
        CREATE TABLE HGB_SURVEY_QUESTIONS (
            QUESTION_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            TEMPLATE_VERSION_ID NUMBER NOT NULL,
            QUESTION_CODE VARCHAR2(80) NOT NULL,
            QUESTION_ORDER NUMBER NOT NULL,
            QUESTION_TYPE VARCHAR2(40) NOT NULL,
            METRIC_TYPE VARCHAR2(20),
            QUESTION_TEXT_TR NVARCHAR2(500) NOT NULL,
            QUESTION_TEXT_EN NVARCHAR2(500),
            QUESTION_TEXT_AR NVARCHAR2(500),
            HELP_TEXT NVARCHAR2(500),
            IS_REQUIRED NUMBER(1) DEFAULT 0,
            IS_INITIAL_QUESTION NUMBER(1) DEFAULT 0,
            MIN_VALUE NUMBER(10,2),
            MAX_VALUE NUMBER(10,2),
            CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
        )]');

    create_table_if_missing('HGB_SURVEY_OPTIONS', q'[
        CREATE TABLE HGB_SURVEY_OPTIONS (
            OPTION_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            QUESTION_ID NUMBER NOT NULL,
            OPTION_ORDER NUMBER NOT NULL,
            OPTION_VALUE VARCHAR2(80) NOT NULL,
            OPTION_TEXT_TR NVARCHAR2(300) NOT NULL,
            OPTION_TEXT_EN NVARCHAR2(300),
            OPTION_TEXT_AR NVARCHAR2(300),
            NUMERIC_VALUE NUMBER(10,2)
        )]');

    create_table_if_missing('HGB_BRANCHING_RULES', q'[
        CREATE TABLE HGB_BRANCHING_RULES (
            BRANCHING_RULE_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            SOURCE_QUESTION_ID NUMBER NOT NULL,
            OPERATOR_CODE VARCHAR2(10) NOT NULL,
            COMPARE_NUMERIC_VALUE NUMBER(10,2),
            COMPARE_OPTION_ID NUMBER,
            TARGET_QUESTION_ID NUMBER NOT NULL,
            RULE_ORDER NUMBER DEFAULT 1,
            IS_ACTIVE NUMBER(1) DEFAULT 1
        )]');

END;
/

MERGE INTO HGB_SCHEMA_VERSION t
USING (
    SELECT '2026-07-schema-03-survey' VERSION_CODE, 'Survey templates, questions and branching' DESCRIPTION
    FROM dual
) s
ON (t.VERSION_CODE = s.VERSION_CODE)
WHEN NOT MATCHED THEN
    INSERT (VERSION_CODE, DESCRIPTION)
    VALUES (s.VERSION_CODE, s.DESCRIPTION);

COMMIT;

PROMPT Step 003 - survey-design tables completed.
