-- Run as the application schema owner. This script can be run again safely.

WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
WHENEVER OSERROR EXIT FAILURE

SET DEFINE OFF;
SET SERVEROUTPUT ON;
SET VERIFY OFF;

PROMPT Step 004 - event and delivery tables started.

DECLARE
    PROCEDURE create_table_if_missing(p_table_name VARCHAR2, p_sql CLOB) IS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_count
        FROM user_tables
        WHERE table_name = UPPER(p_table_name);

        IF v_count = 0 THEN
            EXECUTE IMMEDIATE p_sql;
            DBMS_OUTPUT.PUT_LINE('created table ' || p_table_name);
        END IF;
    END;
BEGIN
    create_table_if_missing('HGB_CHANNELS', q'[
        CREATE TABLE HGB_CHANNELS (
            CHANNEL_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            CHANNEL_CODE VARCHAR2(30) UNIQUE NOT NULL,
            CHANNEL_NAME NVARCHAR2(100) NOT NULL,
            IS_ENABLED NUMBER(1) DEFAULT 1,
            CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
        )]');

    create_table_if_missing('HGB_CHANNEL_TEMPLATES', q'[
        CREATE TABLE HGB_CHANNEL_TEMPLATES (
            CHANNEL_TEMPLATE_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            CHANNEL_ID NUMBER NOT NULL,
            TEMPLATE_CODE VARCHAR2(80) NOT NULL,
            LANGUAGE_CODE VARCHAR2(5) DEFAULT 'tr',
            BODY_TEMPLATE NVARCHAR2(1000) NOT NULL,
            IS_ACTIVE NUMBER(1) DEFAULT 1,
            CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
        )]');

    create_table_if_missing('HGB_TRIGGER_RULES', q'[
        CREATE TABLE HGB_TRIGGER_RULES (
            TRIGGER_RULE_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            EVENT_TYPE VARCHAR2(60) NOT NULL,
            SURVEY_TEMPLATE_ID NUMBER NOT NULL,
            PRIMARY_CHANNEL_ID NUMBER NOT NULL,
            FALLBACK_CHANNEL_ID NUMBER,
            IS_ENABLED NUMBER(1) DEFAULT 1,
            DELAY_MINUTES NUMBER DEFAULT 0,
            LOW_SCORE_THRESHOLD NUMBER(10,2) DEFAULT 3,
            FREQUENCY_CAP_DAYS NUMBER DEFAULT 7,
            FREQUENCY_CAP_COUNT NUMBER DEFAULT 1,
            REMINDER_ENABLED NUMBER(1) DEFAULT 1,
            REMINDER_COUNT NUMBER DEFAULT 1,
            REMINDER_INTERVAL_MINUTES NUMBER DEFAULT 1440,
            SERVICE_RECOVERY_SLA_HOURS NUMBER DEFAULT 24,
            CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
            UPDATED_AT TIMESTAMP
        )]');

    create_table_if_missing('HGB_CLINICAL_EVENTS', q'[
        CREATE TABLE HGB_CLINICAL_EVENTS (
            CLINICAL_EVENT_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            EXTERNAL_EVENT_REF VARCHAR2(120),
            SOURCE_SYSTEM VARCHAR2(80),
            EVENT_TYPE VARCHAR2(60) NOT NULL,
            PATIENT_ID NUMBER,
            HOSPITAL_ID NUMBER,
            BRANCH_ID NUMBER,
            DEPARTMENT_ID NUMBER,
            DOCTOR_ID NUMBER,
            SERVICE_ID NUMBER,
            EVENT_TIME TIMESTAMP NOT NULL,
            IS_SENSITIVE NUMBER(1) DEFAULT 0,
            SENSITIVITY_REASON NVARCHAR2(500),
            STATUS VARCHAR2(30) DEFAULT 'RECEIVED',
            PROCESSED_AT TIMESTAMP,
            CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
        )]');

    create_table_if_missing('HGB_EVENT_QUEUE', q'[
        CREATE TABLE HGB_EVENT_QUEUE (
            QUEUE_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            CLINICAL_EVENT_ID NUMBER NOT NULL,
            QUEUE_STATUS VARCHAR2(30) DEFAULT 'WAITING',
            SCHEDULED_AT TIMESTAMP NOT NULL,
            RETRY_COUNT NUMBER DEFAULT 0,
            STARTED_AT TIMESTAMP,
            COMPLETED_AT TIMESTAMP,
            LAST_ERROR_MESSAGE NVARCHAR2(1000),
            CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
        )]');

    create_table_if_missing('HGB_SURVEY_INVITATIONS', q'[
        CREATE TABLE HGB_SURVEY_INVITATIONS (
            INVITATION_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            CLINICAL_EVENT_ID NUMBER NOT NULL,
            PATIENT_ID NUMBER,
            TEMPLATE_VERSION_ID NUMBER NOT NULL,
            TRIGGER_RULE_ID NUMBER,
            SELECTED_CHANNEL_ID NUMBER,
            TOKEN_HASH VARCHAR2(128) NOT NULL,
            TOKEN_EXPIRES_AT TIMESTAMP NOT NULL,
            TOKEN_USED_AT TIMESTAMP,
            INVITATION_STATUS VARCHAR2(30) DEFAULT 'CREATED',
            SENT_AT TIMESTAMP,
            COMPLETED_AT TIMESTAMP,
            CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
        )]');

    create_table_if_missing('HGB_DELIVERY_ATTEMPTS', q'[
        CREATE TABLE HGB_DELIVERY_ATTEMPTS (
            DELIVERY_ATTEMPT_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            INVITATION_ID NUMBER NOT NULL,
            CHANNEL_ID NUMBER NOT NULL,
            ATTEMPT_NO NUMBER NOT NULL,
            DELIVERY_STATUS VARCHAR2(30) NOT NULL,
            SENT_AT TIMESTAMP,
            FAILED_AT TIMESTAMP,
            ERROR_MESSAGE NVARCHAR2(1000),
            CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
        )]');

END;
/

MERGE INTO HGB_SCHEMA_VERSION t
USING (
    SELECT '2026-07-schema-04-delivery' VERSION_CODE, 'Clinical events, channels, queue and invitations' DESCRIPTION
    FROM dual
) s
ON (t.VERSION_CODE = s.VERSION_CODE)
WHEN NOT MATCHED THEN
    INSERT (VERSION_CODE, DESCRIPTION)
    VALUES (s.VERSION_CODE, s.DESCRIPTION);

COMMIT;

PROMPT Step 004 - event and delivery tables completed.
