-- Run as the application schema owner. This script can be run again safely.

WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
WHENEVER OSERROR EXIT FAILURE

SET DEFINE OFF;
SET SERVEROUTPUT ON;
SET VERIFY OFF;

PROMPT Step 005 - feedback and recovery tables started.

DECLARE
    PROCEDURE create_table_if_missing(p_table_name VARCHAR2, p_sql CLOB) IS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_count
        FROM user_tables
        WHERE table_name = UPPER(p_table_name);

        IF v_count = 0 THEN
            EXECUTE IMMEDIATE p_sql;
            DBMS_OUTPUT.PUT_LINE('created table ' || p_table_name);
        END IF;
    END;
BEGIN
    create_table_if_missing('HGB_CONSENT_TEXTS', q'[
        CREATE TABLE HGB_CONSENT_TEXTS (
            CONSENT_TEXT_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            LANGUAGE_CODE VARCHAR2(5) NOT NULL,
            VERSION_NO NUMBER DEFAULT 1,
            BODY CLOB NOT NULL,
            STATUS VARCHAR2(20) DEFAULT 'ACTIVE',
            CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
        )]');

    create_table_if_missing('HGB_CONSENT_RECORDS', q'[
        CREATE TABLE HGB_CONSENT_RECORDS (
            CONSENT_RECORD_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            INVITATION_ID NUMBER NOT NULL,
            PATIENT_ID NUMBER,
            CONSENT_TEXT_ID NUMBER,
            CONSENT_STATUS VARCHAR2(20) NOT NULL,
            CONSENT_SCOPE VARCHAR2(80),
            ANONYMOUS_SELECTED NUMBER(1) DEFAULT 0,
            IP_HASH VARCHAR2(256),
            GIVEN_AT TIMESTAMP DEFAULT SYSTIMESTAMP
        )]');

    create_table_if_missing('HGB_SURVEY_RESPONSES', q'[
        CREATE TABLE HGB_SURVEY_RESPONSES (
            RESPONSE_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            INVITATION_ID NUMBER NOT NULL,
            CLINICAL_EVENT_ID NUMBER,
            PATIENT_ID NUMBER,
            TEMPLATE_VERSION_ID NUMBER NOT NULL,
            HOSPITAL_ID NUMBER,
            BRANCH_ID NUMBER,
            DEPARTMENT_ID NUMBER,
            DOCTOR_ID NUMBER,
            SERVICE_ID NUMBER,
            CONSENT_RECORD_ID NUMBER,
            IS_ANONYMOUS NUMBER(1) DEFAULT 0,
            OVERALL_SCORE NUMBER(10,2),
            NPS_SCORE NUMBER(10,2),
            CSAT_SCORE NUMBER(10,2),
            IS_NEGATIVE NUMBER(1) DEFAULT 0,
            SENTIMENT_LABEL VARCHAR2(30),
            SENTIMENT_SCORE NUMBER(10,4),
            RESPONSE_STATUS VARCHAR2(30) DEFAULT 'STARTED',
            SUBMITTED_AT TIMESTAMP,
            CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
        )]');

    create_table_if_missing('HGB_SURVEY_ANSWERS', q'[
        CREATE TABLE HGB_SURVEY_ANSWERS (
            ANSWER_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            RESPONSE_ID NUMBER NOT NULL,
            QUESTION_ID NUMBER NOT NULL,
            OPTION_ID NUMBER,
            NUMERIC_VALUE NUMBER(10,2),
            TEXT_VALUE CLOB,
            ANSWERED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
            CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
        )]');

    create_table_if_missing('HGB_ALERTS', q'[
        CREATE TABLE HGB_ALERTS (
            ALERT_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            ALERT_TYPE VARCHAR2(50) NOT NULL,
            SEVERITY VARCHAR2(20) DEFAULT 'MEDIUM',
            ALERT_STATUS VARCHAR2(30) DEFAULT 'OPEN',
            RESPONSE_ID NUMBER,
            CLINICAL_EVENT_ID NUMBER,
            MESSAGE NVARCHAR2(1000) NOT NULL,
            TARGET_USER_ID NUMBER,
            ACKNOWLEDGED_AT TIMESTAMP,
            CLOSED_AT TIMESTAMP,
            CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
        )]');

    create_table_if_missing('HGB_SERVICE_RECOVERY_CASES', q'[
        CREATE TABLE HGB_SERVICE_RECOVERY_CASES (
            RECOVERY_CASE_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            ALERT_ID NUMBER,
            RESPONSE_ID NUMBER NOT NULL,
            DEPARTMENT_ID NUMBER,
            CASE_STATUS VARCHAR2(30) DEFAULT 'OPEN',
            PRIORITY VARCHAR2(20) DEFAULT 'MEDIUM',
            ASSIGNED_USER_ID NUMBER,
            SLA_DUE_AT TIMESTAMP,
            OPENED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
            CLOSED_AT TIMESTAMP,
            CLOSURE_NOTE NVARCHAR2(1000),
            ESCALATION_LEVEL NUMBER DEFAULT 0,
            CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
        )]');

    create_table_if_missing('HGB_RECOVERY_ACTIONS', q'[
        CREATE TABLE HGB_RECOVERY_ACTIONS (
            RECOVERY_ACTION_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            RECOVERY_CASE_ID NUMBER NOT NULL,
            ACTION_TYPE VARCHAR2(50) NOT NULL,
            ACTION_BY_USER_ID NUMBER,
            ACTION_NOTE NVARCHAR2(1000),
            ACTION_AT TIMESTAMP DEFAULT SYSTIMESTAMP
        )]');

    create_table_if_missing('HGB_CASE_ESCALATIONS', q'[
        CREATE TABLE HGB_CASE_ESCALATIONS (
            CASE_ESCALATION_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            RECOVERY_CASE_ID NUMBER NOT NULL,
            ESCALATION_REASON NVARCHAR2(1000),
            CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
        )]');

END;
/

MERGE INTO HGB_SCHEMA_VERSION t
USING (
    SELECT '2026-07-schema-05-feedback' VERSION_CODE, 'Consent, responses, alerts and recovery cases' DESCRIPTION
    FROM dual
) s
ON (t.VERSION_CODE = s.VERSION_CODE)
WHEN NOT MATCHED THEN
    INSERT (VERSION_CODE, DESCRIPTION)
    VALUES (s.VERSION_CODE, s.DESCRIPTION);

COMMIT;

PROMPT Step 005 - feedback and recovery tables completed.
