-- Run as the application schema owner. This script can be run again safely.

WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
WHENEVER OSERROR EXIT FAILURE

SET DEFINE OFF;
SET SERVEROUTPUT ON;
SET VERIFY OFF;

PROMPT Step 006 - operations and integration tables started.

DECLARE
    PROCEDURE create_table_if_missing(p_table_name VARCHAR2, p_sql CLOB) IS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_count
        FROM user_tables
        WHERE table_name = UPPER(p_table_name);

        IF v_count = 0 THEN
            EXECUTE IMMEDIATE p_sql;
            DBMS_OUTPUT.PUT_LINE('created table ' || p_table_name);
        END IF;
    END;
BEGIN
    create_table_if_missing('HGB_AUDIT_LOGS', q'[
        CREATE TABLE HGB_AUDIT_LOGS (
            AUDIT_LOG_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            ENTITY_NAME VARCHAR2(100) NOT NULL,
            ENTITY_ID NUMBER,
            ACTION_CODE VARCHAR2(100) NOT NULL,
            ACTOR_USER_ID NUMBER,
            PATIENT_ID NUMBER,
            CHANGE_DESCRIPTION NVARCHAR2(1000),
            IP_HASH VARCHAR2(256),
            CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
        )]');

    create_table_if_missing('HGB_WEBHOOK_REPLAY', q'[
        CREATE TABLE HGB_WEBHOOK_REPLAY (
            WEBHOOK_REPLAY_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            SIGNATURE_HASH VARCHAR2(128) NOT NULL,
            SOURCE_SYSTEM VARCHAR2(80) NOT NULL,
            RECEIVED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
            EXPIRES_AT TIMESTAMP NOT NULL
        )]');

    create_table_if_missing('HGB_INTEGRATION_SYSTEMS', q'[
        CREATE TABLE HGB_INTEGRATION_SYSTEMS (
            INTEGRATION_SYSTEM_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            SYSTEM_CODE VARCHAR2(80) UNIQUE NOT NULL,
            SYSTEM_NAME NVARCHAR2(200) NOT NULL,
            BASE_URL VARCHAR2(500),
            IS_ENABLED NUMBER(1) DEFAULT 1,
            AUTH_TYPE VARCHAR2(50),
            CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
        )]');

    create_table_if_missing('HGB_INTEGRATION_LOGS', q'[
        CREATE TABLE HGB_INTEGRATION_LOGS (
            INTEGRATION_LOG_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            INTEGRATION_SYSTEM_ID NUMBER,
            DIRECTION VARCHAR2(20) NOT NULL,
            OPERATION_NAME VARCHAR2(100) NOT NULL,
            REQUEST_PAYLOAD CLOB,
            RESPONSE_PAYLOAD CLOB,
            HTTP_STATUS_CODE NUMBER,
            SUCCESS_FLAG NUMBER(1) DEFAULT 0,
            ERROR_MESSAGE NVARCHAR2(1000),
            PROVIDER_MESSAGE_ID VARCHAR2(200),
            CORRELATION_ID VARCHAR2(80),
            RETRY_COUNT NUMBER DEFAULT 0,
            NEXT_RETRY_AT TIMESTAMP,
            CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
        )]');

    create_table_if_missing('HGB_APP_SETTINGS', q'[
        CREATE TABLE HGB_APP_SETTINGS (
            SETTING_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            SETTING_KEY VARCHAR2(120) UNIQUE NOT NULL,
            SETTING_VALUE VARCHAR2(1000),
            DESCRIPTION NVARCHAR2(1000),
            UPDATED_BY_USER_ID NUMBER,
            UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
        )]');

    create_table_if_missing('HGB_KPI_TARGETS', q'[
        CREATE TABLE HGB_KPI_TARGETS (
            KPI_TARGET_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            KPI_CODE VARCHAR2(50) NOT NULL,
            DEPARTMENT_ID NUMBER,
            TARGET_PERIOD VARCHAR2(20) DEFAULT 'MONTH',
            TARGET_VALUE NUMBER(10,2) NOT NULL,
            VALID_FROM DATE DEFAULT SYSDATE,
            VALID_TO DATE,
            CREATED_BY_USER_ID NUMBER,
            CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
        )]');

    create_table_if_missing('HGB_REPORT_EXPORTS', q'[
        CREATE TABLE HGB_REPORT_EXPORTS (
            REPORT_EXPORT_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            REQUESTED_BY_USER_ID NUMBER,
            REPORT_TYPE VARCHAR2(80) NOT NULL,
            EXPORT_FORMAT VARCHAR2(20) NOT NULL,
            FILTER_JSON CLOB,
            EXPORT_STATUS VARCHAR2(30) DEFAULT 'PROCESSING',
            ERROR_MESSAGE NVARCHAR2(1000),
            REQUESTED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
            COMPLETED_AT TIMESTAMP
        )]');

    create_table_if_missing('HGB_RETENTION_POLICIES', q'[
        CREATE TABLE HGB_RETENTION_POLICIES (
            RETENTION_POLICY_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            DATA_CATEGORY VARCHAR2(80) UNIQUE NOT NULL,
            RETENTION_DAYS NUMBER NOT NULL,
            ACTION_AFTER_RETENTION VARCHAR2(30) NOT NULL,
            IS_ACTIVE NUMBER(1) DEFAULT 1
        )]');

    create_table_if_missing('HGB_BI_EXPORT_QUEUE', q'[
        CREATE TABLE HGB_BI_EXPORT_QUEUE (
            BI_EXPORT_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            RESPONSE_ID NUMBER NOT NULL,
            EXPORT_STATUS VARCHAR2(30) DEFAULT 'WAITING',
            RETRY_COUNT NUMBER DEFAULT 0,
            NEXT_RETRY_AT TIMESTAMP,
            LAST_ERROR_MESSAGE NVARCHAR2(1000),
            CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
            EXPORTED_AT TIMESTAMP
        )]');

    create_table_if_missing('HGB_SENTIMENT_RESULTS', q'[
        CREATE TABLE HGB_SENTIMENT_RESULTS (
            SENTIMENT_RESULT_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            RESPONSE_ID NUMBER NOT NULL,
            SOURCE_ANSWER_ID NUMBER,
            MODEL_NAME VARCHAR2(100),
            SENTIMENT_LABEL VARCHAR2(30),
            SENTIMENT_SCORE NUMBER(10,4),
            CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
        )]');

    create_table_if_missing('HGB_THEME_CATEGORIES', q'[
        CREATE TABLE HGB_THEME_CATEGORIES (
            THEME_CATEGORY_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            THEME_CODE VARCHAR2(80) UNIQUE NOT NULL,
            THEME_NAME NVARCHAR2(200) NOT NULL,
            IS_ACTIVE NUMBER(1) DEFAULT 1
        )]');

    create_table_if_missing('HGB_RESPONSE_THEME_MATCHES', q'[
        CREATE TABLE HGB_RESPONSE_THEME_MATCHES (
            RESPONSE_THEME_MATCH_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            RESPONSE_ID NUMBER NOT NULL,
            THEME_CATEGORY_ID NUMBER NOT NULL,
            CONFIDENCE_SCORE NUMBER(10,4),
            CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
        )]');

    create_table_if_missing('HGB_DATA_SUBJECT_REQUESTS', q'[
        CREATE TABLE HGB_DATA_SUBJECT_REQUESTS (
            DSR_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            PATIENT_ID NUMBER,
            REQUEST_TYPE VARCHAR2(30) NOT NULL,
            REQUEST_STATUS VARCHAR2(30) DEFAULT 'OPEN',
            REQUESTED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
            COMPLETED_AT TIMESTAMP,
            REQUESTED_BY_NOTE NVARCHAR2(1000),
            HANDLED_BY_USER_ID NUMBER,
            RESOLUTION_NOTE NVARCHAR2(1000)
        )]');
END;
/

MERGE INTO HGB_SCHEMA_VERSION t
USING (
    SELECT '2026-07-schema-06-operations' VERSION_CODE, 'Audit, integrations, exports, sentiment and compliance' DESCRIPTION
    FROM dual
) s
ON (t.VERSION_CODE = s.VERSION_CODE)
WHEN NOT MATCHED THEN
    INSERT (VERSION_CODE, DESCRIPTION)
    VALUES (s.VERSION_CODE, s.DESCRIPTION);

COMMIT;

PROMPT Step 006 - operations and integration tables completed.
