-- Run as the application schema owner. This script can be run again safely.

WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
WHENEVER OSERROR EXIT FAILURE

SET DEFINE OFF;
SET SERVEROUTPUT ON;
SET VERIFY OFF;

PROMPT Step 007 - application indexes started.

DECLARE
    PROCEDURE create_index_if_missing(p_index_name VARCHAR2, p_sql VARCHAR2) IS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_count
        FROM user_indexes
        WHERE index_name = UPPER(p_index_name);

        IF v_count = 0 THEN
            EXECUTE IMMEDIATE p_sql;
            DBMS_OUTPUT.PUT_LINE('created index ' || p_index_name);
        END IF;
    END;
BEGIN
    create_index_if_missing('UX_HGB_INV_TOKEN', 'CREATE UNIQUE INDEX UX_HGB_INV_TOKEN ON HGB_SURVEY_INVITATIONS(TOKEN_HASH)');
    create_index_if_missing('IX_HGB_EVENTS_STATUS', 'CREATE INDEX IX_HGB_EVENTS_STATUS ON HGB_CLINICAL_EVENTS(STATUS, EVENT_TIME)');
    create_index_if_missing('IX_HGB_QUEUE_STATUS', 'CREATE INDEX IX_HGB_QUEUE_STATUS ON HGB_EVENT_QUEUE(QUEUE_STATUS, SCHEDULED_AT)');
    create_index_if_missing('IX_HGB_RESP_SUBMITTED', 'CREATE INDEX IX_HGB_RESP_SUBMITTED ON HGB_SURVEY_RESPONSES(RESPONSE_STATUS, SUBMITTED_AT)');
    create_index_if_missing('UX_HGB_USER_SCOPES_ACTIVE', 'CREATE UNIQUE INDEX UX_HGB_USER_SCOPES_ACTIVE ON HGB_USER_SCOPES(USER_ID, SCOPE_TYPE, SCOPE_ID, IS_ACTIVE)');
    create_index_if_missing('UX_HGB_WEBHOOK_REPLAY', 'CREATE UNIQUE INDEX UX_HGB_WEBHOOK_REPLAY ON HGB_WEBHOOK_REPLAY(SIGNATURE_HASH, SOURCE_SYSTEM)');
    create_index_if_missing('IX_HGB_WEBHOOK_REPLAY_AT', 'CREATE INDEX IX_HGB_WEBHOOK_REPLAY_AT ON HGB_WEBHOOK_REPLAY(RECEIVED_AT)');
    create_index_if_missing('IX_HGB_USER_SCOPES_USER', 'CREATE INDEX IX_HGB_USER_SCOPES_USER ON HGB_USER_SCOPES(USER_ID, IS_ACTIVE)');
    create_index_if_missing('UX_HGB_CLINICAL_EVENT_EXT', 'CREATE UNIQUE INDEX UX_HGB_CLINICAL_EVENT_EXT ON HGB_CLINICAL_EVENTS(SOURCE_SYSTEM, EXTERNAL_EVENT_REF)');
    create_index_if_missing('IX_HGB_BI_EXPORT_RETRY', 'CREATE INDEX IX_HGB_BI_EXPORT_RETRY ON HGB_BI_EXPORT_QUEUE(EXPORT_STATUS, NEXT_RETRY_AT)');
    create_index_if_missing('UX_HGB_RESP_INVITATION', 'CREATE UNIQUE INDEX UX_HGB_RESP_INVITATION ON HGB_SURVEY_RESPONSES(INVITATION_ID)');
    create_index_if_missing('UX_HGB_ANSWER_QUESTION', 'CREATE UNIQUE INDEX UX_HGB_ANSWER_QUESTION ON HGB_SURVEY_ANSWERS(RESPONSE_ID, QUESTION_ID)');
    create_index_if_missing('UX_HGB_TRIGGER_EVENT', 'CREATE UNIQUE INDEX UX_HGB_TRIGGER_EVENT ON HGB_TRIGGER_RULES(EVENT_TYPE)');
    create_index_if_missing('UX_HGB_DELIVERY_ATTEMPT', 'CREATE UNIQUE INDEX UX_HGB_DELIVERY_ATTEMPT ON HGB_DELIVERY_ATTEMPTS(INVITATION_ID, ATTEMPT_NO)');
    create_index_if_missing('UX_HGB_TEMPLATE_VERSION', 'CREATE UNIQUE INDEX UX_HGB_TEMPLATE_VERSION ON HGB_SURVEY_TEMPLATE_VERSIONS(SURVEY_TEMPLATE_ID, VERSION_NO)');
    create_index_if_missing('UX_HGB_QUESTION_CODE', 'CREATE UNIQUE INDEX UX_HGB_QUESTION_CODE ON HGB_SURVEY_QUESTIONS(TEMPLATE_VERSION_ID, QUESTION_CODE)');
    create_index_if_missing('UX_HGB_QUESTION_ORDER', 'CREATE UNIQUE INDEX UX_HGB_QUESTION_ORDER ON HGB_SURVEY_QUESTIONS(TEMPLATE_VERSION_ID, QUESTION_ORDER)');
    create_index_if_missing('UX_HGB_OPTION_VALUE', 'CREATE UNIQUE INDEX UX_HGB_OPTION_VALUE ON HGB_SURVEY_OPTIONS(QUESTION_ID, OPTION_VALUE)');
    create_index_if_missing('UX_HGB_OPTION_ORDER', 'CREATE UNIQUE INDEX UX_HGB_OPTION_ORDER ON HGB_SURVEY_OPTIONS(QUESTION_ID, OPTION_ORDER)');
    create_index_if_missing('UX_HGB_BRANCH_RULE_ORDER', 'CREATE UNIQUE INDEX UX_HGB_BRANCH_RULE_ORDER ON HGB_BRANCHING_RULES(SOURCE_QUESTION_ID, RULE_ORDER)');
    create_index_if_missing('UX_HGB_CHANNEL_TEMPLATE', 'CREATE UNIQUE INDEX UX_HGB_CHANNEL_TEMPLATE ON HGB_CHANNEL_TEMPLATES(CHANNEL_ID, TEMPLATE_CODE, LANGUAGE_CODE)');
    create_index_if_missing('UX_HGB_RESPONSE_THEME', 'CREATE UNIQUE INDEX UX_HGB_RESPONSE_THEME ON HGB_RESPONSE_THEME_MATCHES(RESPONSE_ID, THEME_CATEGORY_ID)');
    create_index_if_missing('IX_HGB_QUEUE_EVENT', 'CREATE INDEX IX_HGB_QUEUE_EVENT ON HGB_EVENT_QUEUE(CLINICAL_EVENT_ID)');
    create_index_if_missing('IX_HGB_INV_PATIENT_CREATED', 'CREATE INDEX IX_HGB_INV_PATIENT_CREATED ON HGB_SURVEY_INVITATIONS(PATIENT_ID, CREATED_AT)');
    create_index_if_missing('IX_HGB_INV_STATUS_CREATED', 'CREATE INDEX IX_HGB_INV_STATUS_CREATED ON HGB_SURVEY_INVITATIONS(INVITATION_STATUS, CREATED_AT)');
    create_index_if_missing('IX_HGB_INV_EVENT', 'CREATE INDEX IX_HGB_INV_EVENT ON HGB_SURVEY_INVITATIONS(CLINICAL_EVENT_ID)');
    create_index_if_missing('IX_HGB_INV_TRIGGER', 'CREATE INDEX IX_HGB_INV_TRIGGER ON HGB_SURVEY_INVITATIONS(TRIGGER_RULE_ID)');
    create_index_if_missing('IX_HGB_ATTEMPT_INV_STATUS', 'CREATE INDEX IX_HGB_ATTEMPT_INV_STATUS ON HGB_DELIVERY_ATTEMPTS(INVITATION_ID, DELIVERY_STATUS, CREATED_AT)');
    create_index_if_missing('IX_HGB_RESP_PATIENT_DATE', 'CREATE INDEX IX_HGB_RESP_PATIENT_DATE ON HGB_SURVEY_RESPONSES(PATIENT_ID, SUBMITTED_AT)');
    create_index_if_missing('IX_HGB_RECOVERY_STATUS_SLA', 'CREATE INDEX IX_HGB_RECOVERY_STATUS_SLA ON HGB_SERVICE_RECOVERY_CASES(CASE_STATUS, SLA_DUE_AT)');
    create_index_if_missing('IX_HGB_RECOVERY_RESPONSE', 'CREATE INDEX IX_HGB_RECOVERY_RESPONSE ON HGB_SERVICE_RECOVERY_CASES(RESPONSE_ID)');
    create_index_if_missing('IX_HGB_RECOVERY_ACTION_CASE', 'CREATE INDEX IX_HGB_RECOVERY_ACTION_CASE ON HGB_RECOVERY_ACTIONS(RECOVERY_CASE_ID, ACTION_AT)');
    create_index_if_missing('IX_HGB_INTLOG_CREATED', 'CREATE INDEX IX_HGB_INTLOG_CREATED ON HGB_INTEGRATION_LOGS(CREATED_AT)');
    create_index_if_missing('IX_HGB_INTLOG_SYSTEM_DATE', 'CREATE INDEX IX_HGB_INTLOG_SYSTEM_DATE ON HGB_INTEGRATION_LOGS(INTEGRATION_SYSTEM_ID, CREATED_AT)');
    create_index_if_missing('IX_HGB_SENTIMENT_RESPONSE', 'CREATE INDEX IX_HGB_SENTIMENT_RESPONSE ON HGB_SENTIMENT_RESULTS(RESPONSE_ID)');
    create_index_if_missing('IX_HGB_DSR_STATUS_DATE', 'CREATE INDEX IX_HGB_DSR_STATUS_DATE ON HGB_DATA_SUBJECT_REQUESTS(REQUEST_STATUS, REQUESTED_AT)');
END;
/

MERGE INTO HGB_SCHEMA_VERSION t
USING (
    SELECT '2026-07-schema-07-indexes' VERSION_CODE, 'Application lookup and queue indexes' DESCRIPTION
    FROM dual
) s
ON (t.VERSION_CODE = s.VERSION_CODE)
WHEN NOT MATCHED THEN
    INSERT (VERSION_CODE, DESCRIPTION)
    VALUES (s.VERSION_CODE, s.DESCRIPTION);

COMMIT;

PROMPT Step 007 - application indexes completed.
