-- Run after the schema scripts. HBYS source IDs and history records do not have foreign keys.

WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
WHENEVER OSERROR EXIT FAILURE

SET DEFINE OFF;
SET SERVEROUTPUT ON;
SET VERIFY OFF;

DECLARE
    PROCEDURE add_fk_if_missing(p_constraint_name VARCHAR2, p_sql VARCHAR2) IS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_count
        FROM user_constraints
        WHERE constraint_name = UPPER(p_constraint_name);

        IF v_count = 0 THEN
            EXECUTE IMMEDIATE p_sql;
            DBMS_OUTPUT.PUT_LINE('created constraint ' || p_constraint_name);
        END IF;
    END;
BEGIN
    add_fk_if_missing('FK_HGB_BRANCH_HOSPITAL',
        'ALTER TABLE HGB_BRANCHES ADD CONSTRAINT FK_HGB_BRANCH_HOSPITAL FOREIGN KEY (HOSPITAL_ID) REFERENCES HGB_HOSPITALS(HOSPITAL_ID)');
    add_fk_if_missing('FK_HGB_DEPT_BRANCH',
        'ALTER TABLE HGB_DEPARTMENTS ADD CONSTRAINT FK_HGB_DEPT_BRANCH FOREIGN KEY (BRANCH_ID) REFERENCES HGB_BRANCHES(BRANCH_ID)');

    add_fk_if_missing('FK_HGB_USER_PRIMARY_ROLE',
        'ALTER TABLE HGB_USERS ADD CONSTRAINT FK_HGB_USER_PRIMARY_ROLE FOREIGN KEY (PRIMARY_ROLE_ID) REFERENCES HGB_ROLES(ROLE_ID)');
    add_fk_if_missing('FK_HGB_USERROLE_USER',
        'ALTER TABLE HGB_USER_ROLES ADD CONSTRAINT FK_HGB_USERROLE_USER FOREIGN KEY (USER_ID) REFERENCES HGB_USERS(USER_ID)');
    add_fk_if_missing('FK_HGB_USERROLE_ROLE',
        'ALTER TABLE HGB_USER_ROLES ADD CONSTRAINT FK_HGB_USERROLE_ROLE FOREIGN KEY (ROLE_ID) REFERENCES HGB_ROLES(ROLE_ID)');
    add_fk_if_missing('FK_HGB_ROLEPERM_ROLE',
        'ALTER TABLE HGB_ROLE_PERMISSIONS ADD CONSTRAINT FK_HGB_ROLEPERM_ROLE FOREIGN KEY (ROLE_ID) REFERENCES HGB_ROLES(ROLE_ID)');
    add_fk_if_missing('FK_HGB_ROLEPERM_PERM',
        'ALTER TABLE HGB_ROLE_PERMISSIONS ADD CONSTRAINT FK_HGB_ROLEPERM_PERM FOREIGN KEY (PERMISSION_ID) REFERENCES HGB_PERMISSIONS(PERMISSION_ID)');
    add_fk_if_missing('FK_HGB_USERSCOPE_USER',
        'ALTER TABLE HGB_USER_SCOPES ADD CONSTRAINT FK_HGB_USERSCOPE_USER FOREIGN KEY (USER_ID) REFERENCES HGB_USERS(USER_ID)');

    add_fk_if_missing('FK_HGB_TMPLVER_TEMPLATE',
        'ALTER TABLE HGB_SURVEY_TEMPLATE_VERSIONS ADD CONSTRAINT FK_HGB_TMPLVER_TEMPLATE FOREIGN KEY (SURVEY_TEMPLATE_ID) REFERENCES HGB_SURVEY_TEMPLATES(SURVEY_TEMPLATE_ID)');
    add_fk_if_missing('FK_HGB_QUESTION_VERSION',
        'ALTER TABLE HGB_SURVEY_QUESTIONS ADD CONSTRAINT FK_HGB_QUESTION_VERSION FOREIGN KEY (TEMPLATE_VERSION_ID) REFERENCES HGB_SURVEY_TEMPLATE_VERSIONS(TEMPLATE_VERSION_ID)');
    add_fk_if_missing('FK_HGB_OPTION_QUESTION',
        'ALTER TABLE HGB_SURVEY_OPTIONS ADD CONSTRAINT FK_HGB_OPTION_QUESTION FOREIGN KEY (QUESTION_ID) REFERENCES HGB_SURVEY_QUESTIONS(QUESTION_ID) ON DELETE CASCADE');
    add_fk_if_missing('FK_HGB_BRANCHRULE_SOURCE',
        'ALTER TABLE HGB_BRANCHING_RULES ADD CONSTRAINT FK_HGB_BRANCHRULE_SOURCE FOREIGN KEY (SOURCE_QUESTION_ID) REFERENCES HGB_SURVEY_QUESTIONS(QUESTION_ID) ON DELETE CASCADE');
    add_fk_if_missing('FK_HGB_BRANCHRULE_TARGET',
        'ALTER TABLE HGB_BRANCHING_RULES ADD CONSTRAINT FK_HGB_BRANCHRULE_TARGET FOREIGN KEY (TARGET_QUESTION_ID) REFERENCES HGB_SURVEY_QUESTIONS(QUESTION_ID) ON DELETE CASCADE');

    add_fk_if_missing('FK_HGB_CHANTMPL_CHANNEL',
        'ALTER TABLE HGB_CHANNEL_TEMPLATES ADD CONSTRAINT FK_HGB_CHANTMPL_CHANNEL FOREIGN KEY (CHANNEL_ID) REFERENCES HGB_CHANNELS(CHANNEL_ID)');
    add_fk_if_missing('FK_HGB_TRIGGER_TEMPLATE',
        'ALTER TABLE HGB_TRIGGER_RULES ADD CONSTRAINT FK_HGB_TRIGGER_TEMPLATE FOREIGN KEY (SURVEY_TEMPLATE_ID) REFERENCES HGB_SURVEY_TEMPLATES(SURVEY_TEMPLATE_ID)');
    add_fk_if_missing('FK_HGB_TRIGGER_PRIMCHAN',
        'ALTER TABLE HGB_TRIGGER_RULES ADD CONSTRAINT FK_HGB_TRIGGER_PRIMCHAN FOREIGN KEY (PRIMARY_CHANNEL_ID) REFERENCES HGB_CHANNELS(CHANNEL_ID)');
    add_fk_if_missing('FK_HGB_TRIGGER_FALLCHAN',
        'ALTER TABLE HGB_TRIGGER_RULES ADD CONSTRAINT FK_HGB_TRIGGER_FALLCHAN FOREIGN KEY (FALLBACK_CHANNEL_ID) REFERENCES HGB_CHANNELS(CHANNEL_ID)');

    add_fk_if_missing('FK_HGB_EVENT_PATIENT',
        'ALTER TABLE HGB_CLINICAL_EVENTS ADD CONSTRAINT FK_HGB_EVENT_PATIENT FOREIGN KEY (PATIENT_ID) REFERENCES HGB_PATIENTS(PATIENT_ID)');
    add_fk_if_missing('FK_HGB_QUEUE_EVENT',
        'ALTER TABLE HGB_EVENT_QUEUE ADD CONSTRAINT FK_HGB_QUEUE_EVENT FOREIGN KEY (CLINICAL_EVENT_ID) REFERENCES HGB_CLINICAL_EVENTS(CLINICAL_EVENT_ID)');
    add_fk_if_missing('FK_HGB_INV_EVENT',
        'ALTER TABLE HGB_SURVEY_INVITATIONS ADD CONSTRAINT FK_HGB_INV_EVENT FOREIGN KEY (CLINICAL_EVENT_ID) REFERENCES HGB_CLINICAL_EVENTS(CLINICAL_EVENT_ID)');
    add_fk_if_missing('FK_HGB_INV_PATIENT',
        'ALTER TABLE HGB_SURVEY_INVITATIONS ADD CONSTRAINT FK_HGB_INV_PATIENT FOREIGN KEY (PATIENT_ID) REFERENCES HGB_PATIENTS(PATIENT_ID)');
    add_fk_if_missing('FK_HGB_INV_VERSION',
        'ALTER TABLE HGB_SURVEY_INVITATIONS ADD CONSTRAINT FK_HGB_INV_VERSION FOREIGN KEY (TEMPLATE_VERSION_ID) REFERENCES HGB_SURVEY_TEMPLATE_VERSIONS(TEMPLATE_VERSION_ID)');
    add_fk_if_missing('FK_HGB_INV_TRIGGER',
        'ALTER TABLE HGB_SURVEY_INVITATIONS ADD CONSTRAINT FK_HGB_INV_TRIGGER FOREIGN KEY (TRIGGER_RULE_ID) REFERENCES HGB_TRIGGER_RULES(TRIGGER_RULE_ID)');
    add_fk_if_missing('FK_HGB_INV_CHANNEL',
        'ALTER TABLE HGB_SURVEY_INVITATIONS ADD CONSTRAINT FK_HGB_INV_CHANNEL FOREIGN KEY (SELECTED_CHANNEL_ID) REFERENCES HGB_CHANNELS(CHANNEL_ID)');
    add_fk_if_missing('FK_HGB_ATTEMPT_INV',
        'ALTER TABLE HGB_DELIVERY_ATTEMPTS ADD CONSTRAINT FK_HGB_ATTEMPT_INV FOREIGN KEY (INVITATION_ID) REFERENCES HGB_SURVEY_INVITATIONS(INVITATION_ID)');
    add_fk_if_missing('FK_HGB_ATTEMPT_CHANNEL',
        'ALTER TABLE HGB_DELIVERY_ATTEMPTS ADD CONSTRAINT FK_HGB_ATTEMPT_CHANNEL FOREIGN KEY (CHANNEL_ID) REFERENCES HGB_CHANNELS(CHANNEL_ID)');

    add_fk_if_missing('FK_HGB_CONSENT_INV',
        'ALTER TABLE HGB_CONSENT_RECORDS ADD CONSTRAINT FK_HGB_CONSENT_INV FOREIGN KEY (INVITATION_ID) REFERENCES HGB_SURVEY_INVITATIONS(INVITATION_ID)');
    add_fk_if_missing('FK_HGB_CONSENT_PATIENT',
        'ALTER TABLE HGB_CONSENT_RECORDS ADD CONSTRAINT FK_HGB_CONSENT_PATIENT FOREIGN KEY (PATIENT_ID) REFERENCES HGB_PATIENTS(PATIENT_ID)');
    add_fk_if_missing('FK_HGB_CONSENT_TEXT',
        'ALTER TABLE HGB_CONSENT_RECORDS ADD CONSTRAINT FK_HGB_CONSENT_TEXT FOREIGN KEY (CONSENT_TEXT_ID) REFERENCES HGB_CONSENT_TEXTS(CONSENT_TEXT_ID)');
    add_fk_if_missing('FK_HGB_RESP_INV',
        'ALTER TABLE HGB_SURVEY_RESPONSES ADD CONSTRAINT FK_HGB_RESP_INV FOREIGN KEY (INVITATION_ID) REFERENCES HGB_SURVEY_INVITATIONS(INVITATION_ID)');
    add_fk_if_missing('FK_HGB_RESP_EVENT',
        'ALTER TABLE HGB_SURVEY_RESPONSES ADD CONSTRAINT FK_HGB_RESP_EVENT FOREIGN KEY (CLINICAL_EVENT_ID) REFERENCES HGB_CLINICAL_EVENTS(CLINICAL_EVENT_ID)');
    add_fk_if_missing('FK_HGB_RESP_VERSION',
        'ALTER TABLE HGB_SURVEY_RESPONSES ADD CONSTRAINT FK_HGB_RESP_VERSION FOREIGN KEY (TEMPLATE_VERSION_ID) REFERENCES HGB_SURVEY_TEMPLATE_VERSIONS(TEMPLATE_VERSION_ID)');
    add_fk_if_missing('FK_HGB_RESP_CONSENT',
        'ALTER TABLE HGB_SURVEY_RESPONSES ADD CONSTRAINT FK_HGB_RESP_CONSENT FOREIGN KEY (CONSENT_RECORD_ID) REFERENCES HGB_CONSENT_RECORDS(CONSENT_RECORD_ID)');
    add_fk_if_missing('FK_HGB_ANSWER_RESPONSE',
        'ALTER TABLE HGB_SURVEY_ANSWERS ADD CONSTRAINT FK_HGB_ANSWER_RESPONSE FOREIGN KEY (RESPONSE_ID) REFERENCES HGB_SURVEY_RESPONSES(RESPONSE_ID)');

    add_fk_if_missing('FK_HGB_ALERT_RESPONSE',
        'ALTER TABLE HGB_ALERTS ADD CONSTRAINT FK_HGB_ALERT_RESPONSE FOREIGN KEY (RESPONSE_ID) REFERENCES HGB_SURVEY_RESPONSES(RESPONSE_ID)');
    add_fk_if_missing('FK_HGB_ALERT_EVENT',
        'ALTER TABLE HGB_ALERTS ADD CONSTRAINT FK_HGB_ALERT_EVENT FOREIGN KEY (CLINICAL_EVENT_ID) REFERENCES HGB_CLINICAL_EVENTS(CLINICAL_EVENT_ID)');
    add_fk_if_missing('FK_HGB_ALERT_TARGET_USER',
        'ALTER TABLE HGB_ALERTS ADD CONSTRAINT FK_HGB_ALERT_TARGET_USER FOREIGN KEY (TARGET_USER_ID) REFERENCES HGB_USERS(USER_ID)');
    add_fk_if_missing('FK_HGB_CASE_ALERT',
        'ALTER TABLE HGB_SERVICE_RECOVERY_CASES ADD CONSTRAINT FK_HGB_CASE_ALERT FOREIGN KEY (ALERT_ID) REFERENCES HGB_ALERTS(ALERT_ID)');
    add_fk_if_missing('FK_HGB_CASE_RESPONSE',
        'ALTER TABLE HGB_SERVICE_RECOVERY_CASES ADD CONSTRAINT FK_HGB_CASE_RESPONSE FOREIGN KEY (RESPONSE_ID) REFERENCES HGB_SURVEY_RESPONSES(RESPONSE_ID)');
    add_fk_if_missing('FK_HGB_CASE_ASSIGNEE',
        'ALTER TABLE HGB_SERVICE_RECOVERY_CASES ADD CONSTRAINT FK_HGB_CASE_ASSIGNEE FOREIGN KEY (ASSIGNED_USER_ID) REFERENCES HGB_USERS(USER_ID)');
    add_fk_if_missing('FK_HGB_ACTION_CASE',
        'ALTER TABLE HGB_RECOVERY_ACTIONS ADD CONSTRAINT FK_HGB_ACTION_CASE FOREIGN KEY (RECOVERY_CASE_ID) REFERENCES HGB_SERVICE_RECOVERY_CASES(RECOVERY_CASE_ID)');
    add_fk_if_missing('FK_HGB_ACTION_USER',
        'ALTER TABLE HGB_RECOVERY_ACTIONS ADD CONSTRAINT FK_HGB_ACTION_USER FOREIGN KEY (ACTION_BY_USER_ID) REFERENCES HGB_USERS(USER_ID)');
    add_fk_if_missing('FK_HGB_ESCALATION_CASE',
        'ALTER TABLE HGB_CASE_ESCALATIONS ADD CONSTRAINT FK_HGB_ESCALATION_CASE FOREIGN KEY (RECOVERY_CASE_ID) REFERENCES HGB_SERVICE_RECOVERY_CASES(RECOVERY_CASE_ID)');

    add_fk_if_missing('FK_HGB_SENTIMENT_RESPONSE',
        'ALTER TABLE HGB_SENTIMENT_RESULTS ADD CONSTRAINT FK_HGB_SENTIMENT_RESPONSE FOREIGN KEY (RESPONSE_ID) REFERENCES HGB_SURVEY_RESPONSES(RESPONSE_ID)');
    add_fk_if_missing('FK_HGB_SENTIMENT_ANSWER',
        'ALTER TABLE HGB_SENTIMENT_RESULTS ADD CONSTRAINT FK_HGB_SENTIMENT_ANSWER FOREIGN KEY (SOURCE_ANSWER_ID) REFERENCES HGB_SURVEY_ANSWERS(ANSWER_ID) ON DELETE SET NULL');
    add_fk_if_missing('FK_HGB_THEMEMATCH_RESPONSE',
        'ALTER TABLE HGB_RESPONSE_THEME_MATCHES ADD CONSTRAINT FK_HGB_THEMEMATCH_RESPONSE FOREIGN KEY (RESPONSE_ID) REFERENCES HGB_SURVEY_RESPONSES(RESPONSE_ID)');
    add_fk_if_missing('FK_HGB_THEMEMATCH_THEME',
        'ALTER TABLE HGB_RESPONSE_THEME_MATCHES ADD CONSTRAINT FK_HGB_THEMEMATCH_THEME FOREIGN KEY (THEME_CATEGORY_ID) REFERENCES HGB_THEME_CATEGORIES(THEME_CATEGORY_ID)');
    add_fk_if_missing('FK_HGB_BIEXPORT_RESPONSE',
        'ALTER TABLE HGB_BI_EXPORT_QUEUE ADD CONSTRAINT FK_HGB_BIEXPORT_RESPONSE FOREIGN KEY (RESPONSE_ID) REFERENCES HGB_SURVEY_RESPONSES(RESPONSE_ID)');
    add_fk_if_missing('FK_HGB_DSR_PATIENT',
        'ALTER TABLE HGB_DATA_SUBJECT_REQUESTS ADD CONSTRAINT FK_HGB_DSR_PATIENT FOREIGN KEY (PATIENT_ID) REFERENCES HGB_PATIENTS(PATIENT_ID)');
    add_fk_if_missing('FK_HGB_DSR_HANDLER',
        'ALTER TABLE HGB_DATA_SUBJECT_REQUESTS ADD CONSTRAINT FK_HGB_DSR_HANDLER FOREIGN KEY (HANDLED_BY_USER_ID) REFERENCES HGB_USERS(USER_ID)');
    add_fk_if_missing('FK_HGB_KPI_DEPARTMENT',
        'ALTER TABLE HGB_KPI_TARGETS ADD CONSTRAINT FK_HGB_KPI_DEPARTMENT FOREIGN KEY (DEPARTMENT_ID) REFERENCES HGB_DEPARTMENTS(DEPARTMENT_ID)');

    add_fk_if_missing('FK_HGB_BRANCHRULE_OPTION',
        'ALTER TABLE HGB_BRANCHING_RULES ADD CONSTRAINT FK_HGB_BRANCHRULE_OPTION FOREIGN KEY (COMPARE_OPTION_ID) REFERENCES HGB_SURVEY_OPTIONS(OPTION_ID) ON DELETE CASCADE');
    add_fk_if_missing('FK_HGB_INTLOG_SYSTEM',
        'ALTER TABLE HGB_INTEGRATION_LOGS ADD CONSTRAINT FK_HGB_INTLOG_SYSTEM FOREIGN KEY (INTEGRATION_SYSTEM_ID) REFERENCES HGB_INTEGRATION_SYSTEMS(INTEGRATION_SYSTEM_ID) ON DELETE SET NULL');
    add_fk_if_missing('FK_HGB_TEMPLATE_CREATOR',
        'ALTER TABLE HGB_SURVEY_TEMPLATES ADD CONSTRAINT FK_HGB_TEMPLATE_CREATOR FOREIGN KEY (CREATED_BY_USER_ID) REFERENCES HGB_USERS(USER_ID) ON DELETE SET NULL');
    add_fk_if_missing('FK_HGB_SETTING_UPDATER',
        'ALTER TABLE HGB_APP_SETTINGS ADD CONSTRAINT FK_HGB_SETTING_UPDATER FOREIGN KEY (UPDATED_BY_USER_ID) REFERENCES HGB_USERS(USER_ID) ON DELETE SET NULL');
    add_fk_if_missing('FK_HGB_KPI_CREATOR',
        'ALTER TABLE HGB_KPI_TARGETS ADD CONSTRAINT FK_HGB_KPI_CREATOR FOREIGN KEY (CREATED_BY_USER_ID) REFERENCES HGB_USERS(USER_ID) ON DELETE SET NULL');
    add_fk_if_missing('FK_HGB_REPORT_REQUESTER',
        'ALTER TABLE HGB_REPORT_EXPORTS ADD CONSTRAINT FK_HGB_REPORT_REQUESTER FOREIGN KEY (REQUESTED_BY_USER_ID) REFERENCES HGB_USERS(USER_ID) ON DELETE SET NULL');
END;
/

MERGE INTO HGB_SCHEMA_VERSION t
USING (
    SELECT '2026-07-schema-09-foreign-keys' VERSION_CODE,
           'Named application foreign-key constraints' DESCRIPTION
    FROM dual
) s
ON (t.VERSION_CODE = s.VERSION_CODE)
WHEN NOT MATCHED THEN
    INSERT (VERSION_CODE, DESCRIPTION)
    VALUES (s.VERSION_CODE, s.DESCRIPTION);

COMMIT;

PROMPT Step 009 - foreign-key constraints completed.
