-- Mock data for local development only. Do not run in production.

WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
WHENEVER OSERROR EXIT FAILURE

SET DEFINE OFF;
SET VERIFY OFF;

PROMPT Demo organization seed started.

MERGE INTO HGB_HOSPITALS t USING (SELECT 'Probel Demo Hastanesi' HOSPITAL_NAME FROM dual) s
ON (t.HOSPITAL_NAME = s.HOSPITAL_NAME)
WHEN NOT MATCHED THEN INSERT (HOSPITAL_NAME) VALUES (s.HOSPITAL_NAME);

MERGE INTO HGB_BRANCHES t USING (
    SELECT (
        SELECT MIN(HOSPITAL_ID)
        FROM HGB_HOSPITALS
        WHERE HOSPITAL_NAME = 'Probel Demo Hastanesi'
    ) HOSPITAL_ID,
    'Merkez Şube' BRANCH_NAME
    FROM dual
) s
ON (t.HOSPITAL_ID = s.HOSPITAL_ID AND t.BRANCH_NAME = s.BRANCH_NAME)
WHEN NOT MATCHED THEN INSERT (HOSPITAL_ID, BRANCH_NAME) VALUES (s.HOSPITAL_ID, s.BRANCH_NAME);

MERGE INTO HGB_DEPARTMENTS t USING (
    SELECT (
        SELECT MIN(b.BRANCH_ID)
        FROM HGB_BRANCHES b
        JOIN HGB_HOSPITALS h ON h.HOSPITAL_ID = b.HOSPITAL_ID
        WHERE h.HOSPITAL_NAME = 'Probel Demo Hastanesi'
          AND b.BRANCH_NAME = 'Merkez Şube'
    ) BRANCH_ID,
    'Dahiliye' DEPARTMENT_NAME
    FROM dual
) s
ON (t.BRANCH_ID = s.BRANCH_ID AND t.DEPARTMENT_NAME = s.DEPARTMENT_NAME)
WHEN NOT MATCHED THEN INSERT (BRANCH_ID, DEPARTMENT_NAME) VALUES (s.BRANCH_ID, s.DEPARTMENT_NAME);

MERGE INTO HGB_DEPARTMENTS t USING (
    SELECT (
        SELECT MIN(b.BRANCH_ID)
        FROM HGB_BRANCHES b
        JOIN HGB_HOSPITALS h ON h.HOSPITAL_ID = b.HOSPITAL_ID
        WHERE h.HOSPITAL_NAME = 'Probel Demo Hastanesi'
          AND b.BRANCH_NAME = 'Merkez Şube'
    ) BRANCH_ID,
    'Ortopedi' DEPARTMENT_NAME
    FROM dual
) s
ON (t.BRANCH_ID = s.BRANCH_ID AND t.DEPARTMENT_NAME = s.DEPARTMENT_NAME)
WHEN NOT MATCHED THEN INSERT (BRANCH_ID, DEPARTMENT_NAME) VALUES (s.BRANCH_ID, s.DEPARTMENT_NAME);

MERGE INTO HGB_DOCTORS t USING (SELECT 'Dr. Ayşe Demir' FULL_NAME FROM dual) s
ON (t.FULL_NAME = s.FULL_NAME)
WHEN NOT MATCHED THEN INSERT (FULL_NAME) VALUES (s.FULL_NAME);

MERGE INTO HGB_SERVICES t USING (SELECT 'Poliklinik Hizmeti' SERVICE_NAME FROM dual) s
ON (t.SERVICE_NAME = s.SERVICE_NAME)
WHEN NOT MATCHED THEN INSERT (SERVICE_NAME) VALUES (s.SERVICE_NAME);

MERGE INTO HGB_SCHEMA_VERSION t
USING (
    SELECT '2026-07-demo-organization' VERSION_CODE,
           'Synthetic organization records for the local demo' DESCRIPTION
    FROM dual
) s
ON (t.VERSION_CODE = s.VERSION_CODE)
WHEN NOT MATCHED THEN
    INSERT (VERSION_CODE, DESCRIPTION)
    VALUES (s.VERSION_CODE, s.DESCRIPTION);

COMMIT;

PROMPT Demo organization seed completed.
