-- Mock settings for local development only. Do not run in production.

WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
WHENEVER OSERROR EXIT FAILURE

SET DEFINE OFF;
SET VERIFY OFF;

MERGE INTO HGB_APP_SETTINGS t
USING (
    SELECT 'PUBLIC_BASE_URL' SETTING_KEY,
           'http://localhost:5080' SETTING_VALUE,
           'Local demo public URL' DESCRIPTION
    FROM dual
) s
ON (t.SETTING_KEY = s.SETTING_KEY)
WHEN MATCHED THEN
    UPDATE SET
        t.SETTING_VALUE = s.SETTING_VALUE,
        t.DESCRIPTION = s.DESCRIPTION,
        t.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN
    INSERT (SETTING_KEY, SETTING_VALUE, DESCRIPTION)
    VALUES (s.SETTING_KEY, s.SETTING_VALUE, s.DESCRIPTION);

MERGE INTO HGB_SCHEMA_VERSION t
USING (
    SELECT '2026-07-demo-settings' VERSION_CODE,
           'Local-only application settings' DESCRIPTION
    FROM dual
) s
ON (t.VERSION_CODE = s.VERSION_CODE)
WHEN NOT MATCHED THEN
    INSERT (VERSION_CODE, DESCRIPTION)
    VALUES (s.VERSION_CODE, s.DESCRIPTION);

COMMIT;

PROMPT Demo step 003 - local application settings completed.
