-- Run as patient_app with SQL*Plus or SQLcl.

WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

SET DEFINE OFF;
SET SERVEROUTPUT ON;
SET VERIFY OFF;

DECLARE
    PROCEDURE create_table_if_missing(p_table_name VARCHAR2, p_sql CLOB) IS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_count FROM user_tables WHERE table_name = UPPER(p_table_name);
        IF v_count = 0 THEN
            EXECUTE IMMEDIATE p_sql;
            DBMS_OUTPUT.PUT_LINE('created table ' || p_table_name);
        END IF;
    END;

    PROCEDURE create_view(p_view_name VARCHAR2, p_sql CLOB) IS
    BEGIN
        EXECUTE IMMEDIATE p_sql;
        DBMS_OUTPUT.PUT_LINE('created/replaced view ' || p_view_name);
    END;

    PROCEDURE create_index_if_missing(p_index_name VARCHAR2, p_sql VARCHAR2) IS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_count FROM user_indexes WHERE index_name = UPPER(p_index_name);
        IF v_count = 0 THEN
            EXECUTE IMMEDIATE p_sql;
        END IF;
    END;
BEGIN
    create_table_if_missing('HGB_HOSPITALS', q'[
        CREATE TABLE HGB_HOSPITALS (
            HOSPITAL_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            HOSPITAL_NAME NVARCHAR2(200) NOT NULL,
            STATUS VARCHAR2(20) DEFAULT 'ACTIVE',
            CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
        )]');

    create_table_if_missing('HGB_BRANCHES', q'[
        CREATE TABLE HGB_BRANCHES (
            BRANCH_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            HOSPITAL_ID NUMBER NOT NULL,
            BRANCH_NAME NVARCHAR2(200) NOT NULL,
            STATUS VARCHAR2(20) DEFAULT 'ACTIVE',
            CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
        )]');

    create_table_if_missing('HGB_DEPARTMENTS', q'[
        CREATE TABLE HGB_DEPARTMENTS (
            DEPARTMENT_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            BRANCH_ID NUMBER NOT NULL,
            DEPARTMENT_NAME NVARCHAR2(200) NOT NULL,
            STATUS VARCHAR2(20) DEFAULT 'ACTIVE',
            CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
        )]');

    create_table_if_missing('HGB_DOCTORS', q'[
        CREATE TABLE HGB_DOCTORS (
            DOCTOR_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            FULL_NAME NVARCHAR2(200) NOT NULL,
            STATUS VARCHAR2(20) DEFAULT 'ACTIVE',
            CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
        )]');

    create_table_if_missing('HGB_SERVICES', q'[
        CREATE TABLE HGB_SERVICES (
            SERVICE_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            SERVICE_NAME NVARCHAR2(200) NOT NULL,
            STATUS VARCHAR2(20) DEFAULT 'ACTIVE',
            CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
        )]');

    create_table_if_missing('HGB_ROLES', q'[
        CREATE TABLE HGB_ROLES (
            ROLE_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            ROLE_CODE VARCHAR2(50) UNIQUE NOT NULL,
            ROLE_NAME NVARCHAR2(150) NOT NULL,
            DESCRIPTION NVARCHAR2(500),
            CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
        )]');

    create_table_if_missing('HGB_PERMISSIONS', q'[
        CREATE TABLE HGB_PERMISSIONS (
            PERMISSION_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            PERMISSION_NAME VARCHAR2(100) UNIQUE NOT NULL,
            MODULE_NAME VARCHAR2(100) NOT NULL,
            CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
        )]');

    create_table_if_missing('HGB_ROLE_PERMISSIONS', q'[
        CREATE TABLE HGB_ROLE_PERMISSIONS (
            ROLE_ID NUMBER NOT NULL,
            PERMISSION_ID NUMBER NOT NULL,
            PRIMARY KEY (ROLE_ID, PERMISSION_ID)
        )]');

    create_table_if_missing('HGB_USERS', q'[
        CREATE TABLE HGB_USERS (
            USER_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            USERNAME VARCHAR2(100) UNIQUE NOT NULL,
            PASSWORD_HASH VARCHAR2(255) NOT NULL,
            FULL_NAME NVARCHAR2(200) NOT NULL,
            EMAIL VARCHAR2(200),
            PRIMARY_ROLE_ID NUMBER,
            STATUS VARCHAR2(20) DEFAULT 'ACTIVE',
            CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
            UPDATED_AT TIMESTAMP
        )]');

    create_table_if_missing('HGB_USER_ROLES', q'[
        CREATE TABLE HGB_USER_ROLES (
            USER_ID NUMBER NOT NULL,
            ROLE_ID NUMBER NOT NULL,
            PRIMARY KEY (USER_ID, ROLE_ID)
        )]');

    create_table_if_missing('HGB_USER_SCOPES', q'[
        CREATE TABLE HGB_USER_SCOPES (
            USER_SCOPE_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            USER_ID NUMBER NOT NULL,
            SCOPE_TYPE VARCHAR2(30) NOT NULL,
            SCOPE_ID NUMBER NOT NULL,
            IS_ACTIVE NUMBER(1) DEFAULT 1,
            CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
        )]');

    create_table_if_missing('HGB_PATIENTS', q'[
        CREATE TABLE HGB_PATIENTS (
            PATIENT_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            EXTERNAL_PATIENT_REF VARCHAR2(100) UNIQUE,
            PSEUDONYM_CODE VARCHAR2(80) DEFAULT RAWTOHEX(SYS_GUID()),
            FULL_NAME NVARCHAR2(200),
            PHONE VARCHAR2(50),
            PHONE_ENC CLOB,
            PHONE_HASH VARCHAR2(128),
            EMAIL VARCHAR2(200),
            EMAIL_ENC CLOB,
            EMAIL_HASH VARCHAR2(128),
            PREFERRED_LANGUAGE VARCHAR2(5) DEFAULT 'tr',
            ALLOW_CONTACT NUMBER(1) DEFAULT 1,
            IS_DELETED NUMBER(1) DEFAULT 0,
            CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
            UPDATED_AT TIMESTAMP
        )]');

    create_table_if_missing('HGB_SURVEY_TEMPLATES', q'[
        CREATE TABLE HGB_SURVEY_TEMPLATES (
            SURVEY_TEMPLATE_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            TEMPLATE_CODE VARCHAR2(80) UNIQUE NOT NULL,
            TEMPLATE_NAME NVARCHAR2(200) NOT NULL,
            DESCRIPTION NVARCHAR2(1000),
            STATUS VARCHAR2(20) DEFAULT 'ACTIVE',
            CREATED_BY_USER_ID NUMBER,
            CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
        )]');

    create_table_if_missing('HGB_SURVEY_TEMPLATE_VERSIONS', q'[
        CREATE TABLE HGB_SURVEY_TEMPLATE_VERSIONS (
            TEMPLATE_VERSION_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            SURVEY_TEMPLATE_ID NUMBER NOT NULL,
            VERSION_NO NUMBER NOT NULL,
            VERSION_LABEL VARCHAR2(50),
            STATUS VARCHAR2(20) DEFAULT 'DRAFT',
            PUBLISHED_AT TIMESTAMP,
            CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
        )]');

    create_table_if_missing('HGB_SURVEY_QUESTIONS', q'[
        CREATE TABLE HGB_SURVEY_QUESTIONS (
            QUESTION_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            TEMPLATE_VERSION_ID NUMBER NOT NULL,
            QUESTION_CODE VARCHAR2(80) NOT NULL,
            QUESTION_ORDER NUMBER NOT NULL,
            QUESTION_TYPE VARCHAR2(40) NOT NULL,
            METRIC_TYPE VARCHAR2(20),
            QUESTION_TEXT_TR NVARCHAR2(500) NOT NULL,
            QUESTION_TEXT_EN NVARCHAR2(500),
            QUESTION_TEXT_AR NVARCHAR2(500),
            HELP_TEXT NVARCHAR2(500),
            IS_REQUIRED NUMBER(1) DEFAULT 0,
            IS_INITIAL_QUESTION NUMBER(1) DEFAULT 0,
            MIN_VALUE NUMBER(10,2),
            MAX_VALUE NUMBER(10,2),
            CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
        )]');

    create_table_if_missing('HGB_SURVEY_OPTIONS', q'[
        CREATE TABLE HGB_SURVEY_OPTIONS (
            OPTION_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            QUESTION_ID NUMBER NOT NULL,
            OPTION_ORDER NUMBER NOT NULL,
            OPTION_VALUE VARCHAR2(80) NOT NULL,
            OPTION_TEXT_TR NVARCHAR2(300) NOT NULL,
            OPTION_TEXT_EN NVARCHAR2(300),
            OPTION_TEXT_AR NVARCHAR2(300),
            NUMERIC_VALUE NUMBER(10,2)
        )]');

    create_table_if_missing('HGB_BRANCHING_RULES', q'[
        CREATE TABLE HGB_BRANCHING_RULES (
            BRANCHING_RULE_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            SOURCE_QUESTION_ID NUMBER NOT NULL,
            OPERATOR_CODE VARCHAR2(10) NOT NULL,
            COMPARE_NUMERIC_VALUE NUMBER(10,2),
            COMPARE_OPTION_ID NUMBER,
            TARGET_QUESTION_ID NUMBER NOT NULL,
            RULE_ORDER NUMBER DEFAULT 1,
            IS_ACTIVE NUMBER(1) DEFAULT 1
        )]');

    create_table_if_missing('HGB_CHANNELS', q'[
        CREATE TABLE HGB_CHANNELS (
            CHANNEL_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            CHANNEL_CODE VARCHAR2(30) UNIQUE NOT NULL,
            CHANNEL_NAME NVARCHAR2(100) NOT NULL,
            IS_ENABLED NUMBER(1) DEFAULT 1,
            CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
        )]');

    create_table_if_missing('HGB_CHANNEL_TEMPLATES', q'[
        CREATE TABLE HGB_CHANNEL_TEMPLATES (
            CHANNEL_TEMPLATE_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            CHANNEL_ID NUMBER NOT NULL,
            TEMPLATE_CODE VARCHAR2(80) NOT NULL,
            LANGUAGE_CODE VARCHAR2(5) DEFAULT 'tr',
            BODY_TEMPLATE NVARCHAR2(1000) NOT NULL,
            IS_ACTIVE NUMBER(1) DEFAULT 1,
            CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
        )]');

    create_table_if_missing('HGB_TRIGGER_RULES', q'[
        CREATE TABLE HGB_TRIGGER_RULES (
            TRIGGER_RULE_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            EVENT_TYPE VARCHAR2(60) NOT NULL,
            SURVEY_TEMPLATE_ID NUMBER NOT NULL,
            PRIMARY_CHANNEL_ID NUMBER NOT NULL,
            FALLBACK_CHANNEL_ID NUMBER,
            IS_ENABLED NUMBER(1) DEFAULT 1,
            DELAY_MINUTES NUMBER DEFAULT 0,
            LOW_SCORE_THRESHOLD NUMBER(10,2) DEFAULT 3,
            FREQUENCY_CAP_DAYS NUMBER DEFAULT 7,
            FREQUENCY_CAP_COUNT NUMBER DEFAULT 1,
            REMINDER_ENABLED NUMBER(1) DEFAULT 1,
            REMINDER_COUNT NUMBER DEFAULT 1,
            REMINDER_INTERVAL_MINUTES NUMBER DEFAULT 1440,
            SERVICE_RECOVERY_SLA_HOURS NUMBER DEFAULT 24,
            CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
            UPDATED_AT TIMESTAMP
        )]');

    create_table_if_missing('HGB_CLINICAL_EVENTS', q'[
        CREATE TABLE HGB_CLINICAL_EVENTS (
            CLINICAL_EVENT_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            EXTERNAL_EVENT_REF VARCHAR2(120),
            SOURCE_SYSTEM VARCHAR2(80),
            EVENT_TYPE VARCHAR2(60) NOT NULL,
            PATIENT_ID NUMBER,
            HOSPITAL_ID NUMBER,
            BRANCH_ID NUMBER,
            DEPARTMENT_ID NUMBER,
            DOCTOR_ID NUMBER,
            SERVICE_ID NUMBER,
            EVENT_TIME TIMESTAMP NOT NULL,
            IS_SENSITIVE NUMBER(1) DEFAULT 0,
            SENSITIVITY_REASON NVARCHAR2(500),
            STATUS VARCHAR2(30) DEFAULT 'RECEIVED',
            PROCESSED_AT TIMESTAMP,
            CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
        )]');

    create_table_if_missing('HGB_EVENT_QUEUE', q'[
        CREATE TABLE HGB_EVENT_QUEUE (
            QUEUE_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            CLINICAL_EVENT_ID NUMBER NOT NULL,
            QUEUE_STATUS VARCHAR2(30) DEFAULT 'WAITING',
            SCHEDULED_AT TIMESTAMP NOT NULL,
            RETRY_COUNT NUMBER DEFAULT 0,
            STARTED_AT TIMESTAMP,
            COMPLETED_AT TIMESTAMP,
            LAST_ERROR_MESSAGE NVARCHAR2(1000),
            CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
        )]');

    create_table_if_missing('HGB_SURVEY_INVITATIONS', q'[
        CREATE TABLE HGB_SURVEY_INVITATIONS (
            INVITATION_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            CLINICAL_EVENT_ID NUMBER NOT NULL,
            PATIENT_ID NUMBER,
            TEMPLATE_VERSION_ID NUMBER NOT NULL,
            TRIGGER_RULE_ID NUMBER,
            SELECTED_CHANNEL_ID NUMBER,
            TOKEN_HASH VARCHAR2(128) NOT NULL,
            TOKEN_EXPIRES_AT TIMESTAMP NOT NULL,
            TOKEN_USED_AT TIMESTAMP,
            INVITATION_STATUS VARCHAR2(30) DEFAULT 'CREATED',
            SENT_AT TIMESTAMP,
            COMPLETED_AT TIMESTAMP,
            CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
        )]');

    create_table_if_missing('HGB_DELIVERY_ATTEMPTS', q'[
        CREATE TABLE HGB_DELIVERY_ATTEMPTS (
            DELIVERY_ATTEMPT_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            INVITATION_ID NUMBER NOT NULL,
            CHANNEL_ID NUMBER NOT NULL,
            ATTEMPT_NO NUMBER NOT NULL,
            DELIVERY_STATUS VARCHAR2(30) NOT NULL,
            SENT_AT TIMESTAMP,
            FAILED_AT TIMESTAMP,
            ERROR_MESSAGE NVARCHAR2(1000),
            CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
        )]');

    create_table_if_missing('HGB_CONSENT_TEXTS', q'[
        CREATE TABLE HGB_CONSENT_TEXTS (
            CONSENT_TEXT_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            LANGUAGE_CODE VARCHAR2(5) NOT NULL,
            VERSION_NO NUMBER DEFAULT 1,
            BODY CLOB NOT NULL,
            STATUS VARCHAR2(20) DEFAULT 'ACTIVE',
            CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
        )]');

    create_table_if_missing('HGB_CONSENT_RECORDS', q'[
        CREATE TABLE HGB_CONSENT_RECORDS (
            CONSENT_RECORD_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            INVITATION_ID NUMBER NOT NULL,
            PATIENT_ID NUMBER,
            CONSENT_TEXT_ID NUMBER,
            CONSENT_STATUS VARCHAR2(20) NOT NULL,
            CONSENT_SCOPE VARCHAR2(80),
            ANONYMOUS_SELECTED NUMBER(1) DEFAULT 0,
            IP_HASH VARCHAR2(256),
            GIVEN_AT TIMESTAMP DEFAULT SYSTIMESTAMP
        )]');

    create_table_if_missing('HGB_SURVEY_RESPONSES', q'[
        CREATE TABLE HGB_SURVEY_RESPONSES (
            RESPONSE_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            INVITATION_ID NUMBER NOT NULL,
            CLINICAL_EVENT_ID NUMBER,
            PATIENT_ID NUMBER,
            TEMPLATE_VERSION_ID NUMBER NOT NULL,
            HOSPITAL_ID NUMBER,
            BRANCH_ID NUMBER,
            DEPARTMENT_ID NUMBER,
            DOCTOR_ID NUMBER,
            SERVICE_ID NUMBER,
            CONSENT_RECORD_ID NUMBER,
            IS_ANONYMOUS NUMBER(1) DEFAULT 0,
            OVERALL_SCORE NUMBER(10,2),
            NPS_SCORE NUMBER(10,2),
            CSAT_SCORE NUMBER(10,2),
            IS_NEGATIVE NUMBER(1) DEFAULT 0,
            SENTIMENT_LABEL VARCHAR2(30),
            SENTIMENT_SCORE NUMBER(10,4),
            RESPONSE_STATUS VARCHAR2(30) DEFAULT 'STARTED',
            SUBMITTED_AT TIMESTAMP,
            CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
        )]');

    create_table_if_missing('HGB_SURVEY_ANSWERS', q'[
        CREATE TABLE HGB_SURVEY_ANSWERS (
            ANSWER_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            RESPONSE_ID NUMBER NOT NULL,
            QUESTION_ID NUMBER NOT NULL,
            OPTION_ID NUMBER,
            NUMERIC_VALUE NUMBER(10,2),
            TEXT_VALUE CLOB,
            ANSWERED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
            CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
        )]');

    create_table_if_missing('HGB_ALERTS', q'[
        CREATE TABLE HGB_ALERTS (
            ALERT_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            ALERT_TYPE VARCHAR2(50) NOT NULL,
            SEVERITY VARCHAR2(20) DEFAULT 'MEDIUM',
            ALERT_STATUS VARCHAR2(30) DEFAULT 'OPEN',
            RESPONSE_ID NUMBER,
            CLINICAL_EVENT_ID NUMBER,
            MESSAGE NVARCHAR2(1000) NOT NULL,
            TARGET_USER_ID NUMBER,
            ACKNOWLEDGED_AT TIMESTAMP,
            CLOSED_AT TIMESTAMP,
            CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
        )]');

    create_table_if_missing('HGB_SERVICE_RECOVERY_CASES', q'[
        CREATE TABLE HGB_SERVICE_RECOVERY_CASES (
            RECOVERY_CASE_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            ALERT_ID NUMBER,
            RESPONSE_ID NUMBER NOT NULL,
            DEPARTMENT_ID NUMBER,
            CASE_STATUS VARCHAR2(30) DEFAULT 'OPEN',
            PRIORITY VARCHAR2(20) DEFAULT 'MEDIUM',
            ASSIGNED_USER_ID NUMBER,
            SLA_DUE_AT TIMESTAMP,
            OPENED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
            CLOSED_AT TIMESTAMP,
            CLOSURE_NOTE NVARCHAR2(1000),
            ESCALATION_LEVEL NUMBER DEFAULT 0,
            CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
        )]');

    create_table_if_missing('HGB_RECOVERY_ACTIONS', q'[
        CREATE TABLE HGB_RECOVERY_ACTIONS (
            RECOVERY_ACTION_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            RECOVERY_CASE_ID NUMBER NOT NULL,
            ACTION_TYPE VARCHAR2(50) NOT NULL,
            ACTION_BY_USER_ID NUMBER,
            ACTION_NOTE NVARCHAR2(1000),
            ACTION_AT TIMESTAMP DEFAULT SYSTIMESTAMP
        )]');

    create_table_if_missing('HGB_CASE_ESCALATIONS', q'[
        CREATE TABLE HGB_CASE_ESCALATIONS (
            CASE_ESCALATION_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            RECOVERY_CASE_ID NUMBER NOT NULL,
            ESCALATION_REASON NVARCHAR2(1000),
            CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
        )]');

    create_table_if_missing('HGB_AUDIT_LOGS', q'[
        CREATE TABLE HGB_AUDIT_LOGS (
            AUDIT_LOG_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            ENTITY_NAME VARCHAR2(100) NOT NULL,
            ENTITY_ID NUMBER,
            ACTION_CODE VARCHAR2(100) NOT NULL,
            ACTOR_USER_ID NUMBER,
            PATIENT_ID NUMBER,
            CHANGE_DESCRIPTION NVARCHAR2(1000),
            IP_HASH VARCHAR2(256),
            CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
        )]');

    create_table_if_missing('HGB_SCHEMA_VERSION', q'[
        CREATE TABLE HGB_SCHEMA_VERSION (
            VERSION_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            VERSION_CODE VARCHAR2(80) UNIQUE NOT NULL,
            DESCRIPTION NVARCHAR2(500),
            APPLIED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
        )]');

    create_table_if_missing('HGB_WEBHOOK_REPLAY', q'[
        CREATE TABLE HGB_WEBHOOK_REPLAY (
            WEBHOOK_REPLAY_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            SIGNATURE_HASH VARCHAR2(128) NOT NULL,
            SOURCE_SYSTEM VARCHAR2(80) NOT NULL,
            RECEIVED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
            EXPIRES_AT TIMESTAMP NOT NULL
        )]');

    create_table_if_missing('HGB_INTEGRATION_SYSTEMS', q'[
        CREATE TABLE HGB_INTEGRATION_SYSTEMS (
            INTEGRATION_SYSTEM_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            SYSTEM_CODE VARCHAR2(80) UNIQUE NOT NULL,
            SYSTEM_NAME NVARCHAR2(200) NOT NULL,
            BASE_URL VARCHAR2(500),
            IS_ENABLED NUMBER(1) DEFAULT 1,
            AUTH_TYPE VARCHAR2(50),
            CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
        )]');

    create_table_if_missing('HGB_INTEGRATION_LOGS', q'[
        CREATE TABLE HGB_INTEGRATION_LOGS (
            INTEGRATION_LOG_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            INTEGRATION_SYSTEM_ID NUMBER,
            DIRECTION VARCHAR2(20) NOT NULL,
            OPERATION_NAME VARCHAR2(100) NOT NULL,
            REQUEST_PAYLOAD CLOB,
            RESPONSE_PAYLOAD CLOB,
            HTTP_STATUS_CODE NUMBER,
            SUCCESS_FLAG NUMBER(1) DEFAULT 0,
            ERROR_MESSAGE NVARCHAR2(1000),
            PROVIDER_MESSAGE_ID VARCHAR2(200),
            CORRELATION_ID VARCHAR2(80),
            RETRY_COUNT NUMBER DEFAULT 0,
            NEXT_RETRY_AT TIMESTAMP,
            CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
        )]');

    create_table_if_missing('HGB_APP_SETTINGS', q'[
        CREATE TABLE HGB_APP_SETTINGS (
            SETTING_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            SETTING_KEY VARCHAR2(120) UNIQUE NOT NULL,
            SETTING_VALUE VARCHAR2(1000),
            DESCRIPTION NVARCHAR2(1000),
            UPDATED_BY_USER_ID NUMBER,
            UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
        )]');

    create_table_if_missing('HGB_KPI_TARGETS', q'[
        CREATE TABLE HGB_KPI_TARGETS (
            KPI_TARGET_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            KPI_CODE VARCHAR2(50) NOT NULL,
            DEPARTMENT_ID NUMBER,
            TARGET_PERIOD VARCHAR2(20) DEFAULT 'MONTH',
            TARGET_VALUE NUMBER(10,2) NOT NULL,
            VALID_FROM DATE DEFAULT SYSDATE,
            VALID_TO DATE,
            CREATED_BY_USER_ID NUMBER,
            CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
        )]');

    create_table_if_missing('HGB_REPORT_EXPORTS', q'[
        CREATE TABLE HGB_REPORT_EXPORTS (
            REPORT_EXPORT_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            REQUESTED_BY_USER_ID NUMBER,
            REPORT_TYPE VARCHAR2(80) NOT NULL,
            EXPORT_FORMAT VARCHAR2(20) NOT NULL,
            FILTER_JSON CLOB,
            EXPORT_STATUS VARCHAR2(30) DEFAULT 'PROCESSING',
            ERROR_MESSAGE NVARCHAR2(1000),
            REQUESTED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
            COMPLETED_AT TIMESTAMP
        )]');

    create_table_if_missing('HGB_RETENTION_POLICIES', q'[
        CREATE TABLE HGB_RETENTION_POLICIES (
            RETENTION_POLICY_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            DATA_CATEGORY VARCHAR2(80) UNIQUE NOT NULL,
            RETENTION_DAYS NUMBER NOT NULL,
            ACTION_AFTER_RETENTION VARCHAR2(30) NOT NULL,
            IS_ACTIVE NUMBER(1) DEFAULT 1
        )]');

    create_table_if_missing('HGB_BI_EXPORT_QUEUE', q'[
        CREATE TABLE HGB_BI_EXPORT_QUEUE (
            BI_EXPORT_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            RESPONSE_ID NUMBER NOT NULL,
            EXPORT_STATUS VARCHAR2(30) DEFAULT 'WAITING',
            RETRY_COUNT NUMBER DEFAULT 0,
            NEXT_RETRY_AT TIMESTAMP,
            LAST_ERROR_MESSAGE NVARCHAR2(1000),
            CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
            EXPORTED_AT TIMESTAMP
        )]');

    create_table_if_missing('HGB_SENTIMENT_RESULTS', q'[
        CREATE TABLE HGB_SENTIMENT_RESULTS (
            SENTIMENT_RESULT_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            RESPONSE_ID NUMBER NOT NULL,
            SOURCE_ANSWER_ID NUMBER,
            MODEL_NAME VARCHAR2(100),
            SENTIMENT_LABEL VARCHAR2(30),
            SENTIMENT_SCORE NUMBER(10,4),
            CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
        )]');

    create_table_if_missing('HGB_THEME_CATEGORIES', q'[
        CREATE TABLE HGB_THEME_CATEGORIES (
            THEME_CATEGORY_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            THEME_CODE VARCHAR2(80) UNIQUE NOT NULL,
            THEME_NAME NVARCHAR2(200) NOT NULL,
            IS_ACTIVE NUMBER(1) DEFAULT 1
        )]');

    create_table_if_missing('HGB_RESPONSE_THEME_MATCHES', q'[
        CREATE TABLE HGB_RESPONSE_THEME_MATCHES (
            RESPONSE_THEME_MATCH_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            RESPONSE_ID NUMBER NOT NULL,
            THEME_CATEGORY_ID NUMBER NOT NULL,
            CONFIDENCE_SCORE NUMBER(10,4),
            CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
        )]');

    create_table_if_missing('HGB_DATA_SUBJECT_REQUESTS', q'[
        CREATE TABLE HGB_DATA_SUBJECT_REQUESTS (
            DSR_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            PATIENT_ID NUMBER,
            REQUEST_TYPE VARCHAR2(30) NOT NULL,
            REQUEST_STATUS VARCHAR2(30) DEFAULT 'OPEN',
            REQUESTED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
            COMPLETED_AT TIMESTAMP,
            REQUESTED_BY_NOTE NVARCHAR2(1000),
            HANDLED_BY_USER_ID NUMBER,
            RESOLUTION_NOTE NVARCHAR2(1000)
        )]');

    create_index_if_missing('IX_HGB_INV_TOKEN', 'CREATE INDEX IX_HGB_INV_TOKEN ON HGB_SURVEY_INVITATIONS(TOKEN_HASH)');
    create_index_if_missing('IX_HGB_EVENTS_STATUS', 'CREATE INDEX IX_HGB_EVENTS_STATUS ON HGB_CLINICAL_EVENTS(STATUS, EVENT_TIME)');
    create_index_if_missing('IX_HGB_QUEUE_STATUS', 'CREATE INDEX IX_HGB_QUEUE_STATUS ON HGB_EVENT_QUEUE(QUEUE_STATUS, SCHEDULED_AT)');
    create_index_if_missing('IX_HGB_RESP_SUBMITTED', 'CREATE INDEX IX_HGB_RESP_SUBMITTED ON HGB_SURVEY_RESPONSES(RESPONSE_STATUS, SUBMITTED_AT)');
    create_index_if_missing('UX_HGB_USER_SCOPES_ACTIVE', 'CREATE UNIQUE INDEX UX_HGB_USER_SCOPES_ACTIVE ON HGB_USER_SCOPES(USER_ID, SCOPE_TYPE, SCOPE_ID, IS_ACTIVE)');
    create_index_if_missing('UX_HGB_WEBHOOK_REPLAY', 'CREATE UNIQUE INDEX UX_HGB_WEBHOOK_REPLAY ON HGB_WEBHOOK_REPLAY(SIGNATURE_HASH, SOURCE_SYSTEM)');
    create_index_if_missing('UX_HGB_CLINICAL_EVENT_EXT', 'CREATE UNIQUE INDEX UX_HGB_CLINICAL_EVENT_EXT ON HGB_CLINICAL_EVENTS(SOURCE_SYSTEM, EXTERNAL_EVENT_REF)');
    create_index_if_missing('IX_HGB_BI_EXPORT_RETRY', 'CREATE INDEX IX_HGB_BI_EXPORT_RETRY ON HGB_BI_EXPORT_QUEUE(EXPORT_STATUS, NEXT_RETRY_AT)');

    create_view('HGB_V_FEEDBACK_DASHBOARD', q'[
        CREATE OR REPLACE VIEW HGB_V_FEEDBACK_DASHBOARD AS
        SELECT
            TRUNC(r.SUBMITTED_AT) REPORT_DATE,
            r.BRANCH_ID,
            r.DEPARTMENT_ID,
            d.DEPARTMENT_NAME,
            r.DOCTOR_ID,
            doc.FULL_NAME DOCTOR_NAME,
            COUNT(*) TOTAL_RESPONSES,
            AVG(r.OVERALL_SCORE) AVG_OVERALL_SCORE,
            AVG(r.CSAT_SCORE) AVG_CSAT_SCORE,
            CASE WHEN COUNT(r.NPS_SCORE) = 0 THEN NULL
                 ELSE ROUND(
                    (
                        SUM(CASE WHEN r.NPS_SCORE >= 9 THEN 1 ELSE 0 END) -
                        SUM(CASE WHEN r.NPS_SCORE <= 6 THEN 1 ELSE 0 END)
                    ) / COUNT(r.NPS_SCORE) * 100, 2)
            END NPS_VALUE,
            SUM(CASE WHEN r.IS_NEGATIVE = 1 THEN 1 ELSE 0 END) NEGATIVE_COUNT,
            CASE WHEN COUNT(*) = 0 THEN 0
                 ELSE ROUND(SUM(CASE WHEN r.IS_NEGATIVE = 1 THEN 1 ELSE 0 END) / COUNT(*) * 100, 2)
            END NEGATIVE_RATE
        FROM HGB_SURVEY_RESPONSES r
        LEFT JOIN HGB_DEPARTMENTS d ON r.DEPARTMENT_ID = d.DEPARTMENT_ID
        LEFT JOIN HGB_DOCTORS doc ON r.DOCTOR_ID = doc.DOCTOR_ID
        WHERE r.RESPONSE_STATUS = 'SUBMITTED'
        GROUP BY TRUNC(r.SUBMITTED_AT), r.BRANCH_ID, r.DEPARTMENT_ID, d.DEPARTMENT_NAME, r.DOCTOR_ID, doc.FULL_NAME]');

    create_view('HGB_V_OPEN_RECOVERY_CASES', q'[
        CREATE OR REPLACE VIEW HGB_V_OPEN_RECOVERY_CASES AS
        SELECT
            c.RECOVERY_CASE_ID,
            c.RESPONSE_ID,
            c.CASE_STATUS,
            c.PRIORITY,
            d.DEPARTMENT_NAME,
            r.OVERALL_SCORE,
            u.FULL_NAME ASSIGNED_USER_NAME,
            c.OPENED_AT,
            c.SLA_DUE_AT,
            CASE WHEN c.SLA_DUE_AT < SYSTIMESTAMP AND c.CASE_STATUS <> 'CLOSED' THEN 1 ELSE 0 END IS_SLA_BREACHED
        FROM HGB_SERVICE_RECOVERY_CASES c
        JOIN HGB_SURVEY_RESPONSES r ON c.RESPONSE_ID = r.RESPONSE_ID
        LEFT JOIN HGB_DEPARTMENTS d ON c.DEPARTMENT_ID = d.DEPARTMENT_ID
        LEFT JOIN HGB_USERS u ON c.ASSIGNED_USER_ID = u.USER_ID
        WHERE c.CASE_STATUS <> 'CLOSED']');
END;
/

MERGE INTO HGB_HOSPITALS t USING (SELECT 'Probel Demo Hastanesi' HOSPITAL_NAME FROM dual) s
ON (t.HOSPITAL_NAME = s.HOSPITAL_NAME)
WHEN NOT MATCHED THEN INSERT (HOSPITAL_NAME) VALUES (s.HOSPITAL_NAME);

MERGE INTO HGB_BRANCHES t USING (SELECT (SELECT MIN(HOSPITAL_ID) FROM HGB_HOSPITALS) HOSPITAL_ID, 'Merkez Şube' BRANCH_NAME FROM dual) s
ON (t.BRANCH_NAME = s.BRANCH_NAME)
WHEN NOT MATCHED THEN INSERT (HOSPITAL_ID, BRANCH_NAME) VALUES (s.HOSPITAL_ID, s.BRANCH_NAME);

MERGE INTO HGB_DEPARTMENTS t USING (SELECT (SELECT MIN(BRANCH_ID) FROM HGB_BRANCHES) BRANCH_ID, 'Dahiliye' DEPARTMENT_NAME FROM dual) s
ON (t.DEPARTMENT_NAME = s.DEPARTMENT_NAME)
WHEN NOT MATCHED THEN INSERT (BRANCH_ID, DEPARTMENT_NAME) VALUES (s.BRANCH_ID, s.DEPARTMENT_NAME);

MERGE INTO HGB_DEPARTMENTS t USING (SELECT (SELECT MIN(BRANCH_ID) FROM HGB_BRANCHES) BRANCH_ID, 'Ortopedi' DEPARTMENT_NAME FROM dual) s
ON (t.DEPARTMENT_NAME = s.DEPARTMENT_NAME)
WHEN NOT MATCHED THEN INSERT (BRANCH_ID, DEPARTMENT_NAME) VALUES (s.BRANCH_ID, s.DEPARTMENT_NAME);

MERGE INTO HGB_DOCTORS t USING (SELECT 'Dr. Ayşe Demir' FULL_NAME FROM dual) s
ON (t.FULL_NAME = s.FULL_NAME)
WHEN NOT MATCHED THEN INSERT (FULL_NAME) VALUES (s.FULL_NAME);

MERGE INTO HGB_SERVICES t USING (SELECT 'Poliklinik Hizmeti' SERVICE_NAME FROM dual) s
ON (t.SERVICE_NAME = s.SERVICE_NAME)
WHEN NOT MATCHED THEN INSERT (SERVICE_NAME) VALUES (s.SERVICE_NAME);

MERGE INTO HGB_ROLES t USING (SELECT 'SYS_ADMIN' ROLE_CODE, 'Sistem Yöneticisi' ROLE_NAME, 'Tüm modül yönetimi' DESCRIPTION FROM dual) s
ON (t.ROLE_CODE = s.ROLE_CODE)
WHEN NOT MATCHED THEN INSERT (ROLE_CODE, ROLE_NAME, DESCRIPTION) VALUES (s.ROLE_CODE, s.ROLE_NAME, s.DESCRIPTION);
MERGE INTO HGB_ROLES t USING (SELECT 'QUALITY_MANAGER' ROLE_CODE, 'Kalite Yöneticisi' ROLE_NAME, 'Dashboard, rapor ve kalite süreçleri' DESCRIPTION FROM dual) s
ON (t.ROLE_CODE = s.ROLE_CODE)
WHEN NOT MATCHED THEN INSERT (ROLE_CODE, ROLE_NAME, DESCRIPTION) VALUES (s.ROLE_CODE, s.ROLE_NAME, s.DESCRIPTION);
MERGE INTO HGB_ROLES t USING (SELECT 'UNIT_MANAGER' ROLE_CODE, 'Birim Sorumlusu' ROLE_NAME, 'Hizmet telafisi ve bölüm aksiyonları' DESCRIPTION FROM dual) s
ON (t.ROLE_CODE = s.ROLE_CODE)
WHEN NOT MATCHED THEN INSERT (ROLE_CODE, ROLE_NAME, DESCRIPTION) VALUES (s.ROLE_CODE, s.ROLE_NAME, s.DESCRIPTION);

MERGE INTO HGB_PERMISSIONS t USING (SELECT 'DASHBOARD_VIEW' PERMISSION_NAME, 'Dashboard' MODULE_NAME FROM dual) s
ON (t.PERMISSION_NAME = s.PERMISSION_NAME)
WHEN NOT MATCHED THEN INSERT (PERMISSION_NAME, MODULE_NAME) VALUES (s.PERMISSION_NAME, s.MODULE_NAME);
MERGE INTO HGB_PERMISSIONS t USING (SELECT 'SURVEY_ADMIN' PERMISSION_NAME, 'Survey' MODULE_NAME FROM dual) s
ON (t.PERMISSION_NAME = s.PERMISSION_NAME)
WHEN NOT MATCHED THEN INSERT (PERMISSION_NAME, MODULE_NAME) VALUES (s.PERMISSION_NAME, s.MODULE_NAME);
MERGE INTO HGB_PERMISSIONS t USING (SELECT 'RECOVERY_MANAGE' PERMISSION_NAME, 'ServiceRecovery' MODULE_NAME FROM dual) s
ON (t.PERMISSION_NAME = s.PERMISSION_NAME)
WHEN NOT MATCHED THEN INSERT (PERMISSION_NAME, MODULE_NAME) VALUES (s.PERMISSION_NAME, s.MODULE_NAME);
MERGE INTO HGB_PERMISSIONS t USING (SELECT 'COMPLIANCE_MANAGE' PERMISSION_NAME, 'Compliance' MODULE_NAME FROM dual) s
ON (t.PERMISSION_NAME = s.PERMISSION_NAME)
WHEN NOT MATCHED THEN INSERT (PERMISSION_NAME, MODULE_NAME) VALUES (s.PERMISSION_NAME, s.MODULE_NAME);

INSERT INTO HGB_ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID)
SELECT r.ROLE_ID, p.PERMISSION_ID
FROM HGB_ROLES r CROSS JOIN HGB_PERMISSIONS p
WHERE r.ROLE_CODE = 'SYS_ADMIN'
  AND NOT EXISTS (SELECT 1 FROM HGB_ROLE_PERMISSIONS rp WHERE rp.ROLE_ID = r.ROLE_ID AND rp.PERMISSION_ID = p.PERMISSION_ID);

INSERT INTO HGB_ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID)
SELECT r.ROLE_ID, p.PERMISSION_ID
FROM HGB_ROLES r JOIN HGB_PERMISSIONS p ON p.PERMISSION_NAME IN ('DASHBOARD_VIEW', 'RECOVERY_MANAGE')
WHERE r.ROLE_CODE IN ('QUALITY_MANAGER', 'UNIT_MANAGER')
  AND NOT EXISTS (SELECT 1 FROM HGB_ROLE_PERMISSIONS rp WHERE rp.ROLE_ID = r.ROLE_ID AND rp.PERMISSION_ID = p.PERMISSION_ID);

INSERT INTO HGB_USER_ROLES (USER_ID, ROLE_ID)
SELECT u.USER_ID, u.PRIMARY_ROLE_ID FROM HGB_USERS u
WHERE NOT EXISTS (SELECT 1 FROM HGB_USER_ROLES ur WHERE ur.USER_ID = u.USER_ID AND ur.ROLE_ID = u.PRIMARY_ROLE_ID);

MERGE INTO HGB_CHANNELS t USING (SELECT 'SMS' CHANNEL_CODE, 'Probel LBYS SMS' CHANNEL_NAME FROM dual) s ON (t.CHANNEL_CODE = s.CHANNEL_CODE)
WHEN NOT MATCHED THEN INSERT (CHANNEL_CODE, CHANNEL_NAME, IS_ENABLED) VALUES (s.CHANNEL_CODE, s.CHANNEL_NAME, 1);
MERGE INTO HGB_CHANNELS t USING (SELECT 'WHATSAPP' CHANNEL_CODE, 'WhatsApp Business' CHANNEL_NAME FROM dual) s ON (t.CHANNEL_CODE = s.CHANNEL_CODE)
WHEN NOT MATCHED THEN INSERT (CHANNEL_CODE, CHANNEL_NAME, IS_ENABLED) VALUES (s.CHANNEL_CODE, s.CHANNEL_NAME, 1);
MERGE INTO HGB_CHANNELS t USING (SELECT 'QR' CHANNEL_CODE, 'QR Kod' CHANNEL_NAME FROM dual) s ON (t.CHANNEL_CODE = s.CHANNEL_CODE)
WHEN NOT MATCHED THEN INSERT (CHANNEL_CODE, CHANNEL_NAME, IS_ENABLED) VALUES (s.CHANNEL_CODE, s.CHANNEL_NAME, 1);
MERGE INTO HGB_CHANNELS t USING (SELECT 'PORTAL' CHANNEL_CODE, 'Hasta Portalı' CHANNEL_NAME FROM dual) s ON (t.CHANNEL_CODE = s.CHANNEL_CODE)
WHEN NOT MATCHED THEN INSERT (CHANNEL_CODE, CHANNEL_NAME, IS_ENABLED) VALUES (s.CHANNEL_CODE, s.CHANNEL_NAME, 1);
MERGE INTO HGB_CHANNELS t USING (SELECT 'KIOSK' CHANNEL_CODE, 'Kiosk' CHANNEL_NAME FROM dual) s ON (t.CHANNEL_CODE = s.CHANNEL_CODE)
WHEN NOT MATCHED THEN INSERT (CHANNEL_CODE, CHANNEL_NAME, IS_ENABLED) VALUES (s.CHANNEL_CODE, s.CHANNEL_NAME, 1);

INSERT INTO HGB_CHANNEL_TEMPLATES (CHANNEL_ID, TEMPLATE_CODE, LANGUAGE_CODE, BODY_TEMPLATE)
SELECT c.CHANNEL_ID, 'SURVEY_INVITE', l.LANG, l.BODY
FROM HGB_CHANNELS c
CROSS JOIN (
    SELECT 'tr' LANG, 'Sayın {{patient_name}}, memnuniyet anketiniz: {{survey_link}}' BODY FROM dual
    UNION ALL SELECT 'en', 'Dear {{patient_name}}, your satisfaction survey: {{survey_link}}' FROM dual
    UNION ALL SELECT 'ar', 'رابط استبيان الرضا: {{survey_link}}' FROM dual
) l
WHERE c.CHANNEL_CODE IN ('SMS', 'WHATSAPP', 'QR', 'PORTAL', 'KIOSK')
  AND NOT EXISTS (
      SELECT 1 FROM HGB_CHANNEL_TEMPLATES ct
      WHERE ct.CHANNEL_ID = c.CHANNEL_ID AND ct.TEMPLATE_CODE = 'SURVEY_INVITE' AND ct.LANGUAGE_CODE = l.LANG
  );

MERGE INTO HGB_INTEGRATION_SYSTEMS t USING (SELECT 'PROBEL_HBYS' SYSTEM_CODE, 'Probel HBYS' SYSTEM_NAME, 'API_KEY' AUTH_TYPE FROM dual) s ON (t.SYSTEM_CODE = s.SYSTEM_CODE)
WHEN NOT MATCHED THEN INSERT (SYSTEM_CODE, SYSTEM_NAME, AUTH_TYPE) VALUES (s.SYSTEM_CODE, s.SYSTEM_NAME, s.AUTH_TYPE);
MERGE INTO HGB_INTEGRATION_SYSTEMS t USING (SELECT 'PROBEL_LBYS_SMS' SYSTEM_CODE, 'Probel LBYS SMS' SYSTEM_NAME, 'API_KEY' AUTH_TYPE FROM dual) s ON (t.SYSTEM_CODE = s.SYSTEM_CODE)
WHEN NOT MATCHED THEN INSERT (SYSTEM_CODE, SYSTEM_NAME, AUTH_TYPE) VALUES (s.SYSTEM_CODE, s.SYSTEM_NAME, s.AUTH_TYPE);
MERGE INTO HGB_INTEGRATION_SYSTEMS t USING (SELECT 'WHATSAPP_BUSINESS' SYSTEM_CODE, 'WhatsApp Business' SYSTEM_NAME, 'BEARER' AUTH_TYPE FROM dual) s ON (t.SYSTEM_CODE = s.SYSTEM_CODE)
WHEN NOT MATCHED THEN INSERT (SYSTEM_CODE, SYSTEM_NAME, AUTH_TYPE) VALUES (s.SYSTEM_CODE, s.SYSTEM_NAME, s.AUTH_TYPE);
MERGE INTO HGB_INTEGRATION_SYSTEMS t USING (SELECT 'PROBEL_BI' SYSTEM_CODE, 'Probel BI' SYSTEM_NAME, 'VIEW' AUTH_TYPE FROM dual) s ON (t.SYSTEM_CODE = s.SYSTEM_CODE)
WHEN NOT MATCHED THEN INSERT (SYSTEM_CODE, SYSTEM_NAME, AUTH_TYPE) VALUES (s.SYSTEM_CODE, s.SYSTEM_NAME, s.AUTH_TYPE);

MERGE INTO HGB_APP_SETTINGS t USING (SELECT 'PUBLIC_BASE_URL' SETTING_KEY, 'http://localhost:5080' SETTING_VALUE, 'Anket linklerinde kullanılan public base URL' DESCRIPTION FROM dual) s
ON (t.SETTING_KEY = s.SETTING_KEY)
WHEN NOT MATCHED THEN INSERT (SETTING_KEY, SETTING_VALUE, DESCRIPTION) VALUES (s.SETTING_KEY, s.SETTING_VALUE, s.DESCRIPTION);
MERGE INTO HGB_APP_SETTINGS t USING (SELECT 'DEFAULT_TOKEN_TTL_HOURS' SETTING_KEY, '72' SETTING_VALUE, 'Davet token süresi' DESCRIPTION FROM dual) s
ON (t.SETTING_KEY = s.SETTING_KEY)
WHEN NOT MATCHED THEN INSERT (SETTING_KEY, SETTING_VALUE, DESCRIPTION) VALUES (s.SETTING_KEY, s.SETTING_VALUE, s.DESCRIPTION);
MERGE INTO HGB_APP_SETTINGS t USING (SELECT 'DEFAULT_LOW_SCORE_THRESHOLD' SETTING_KEY, '3' SETTING_VALUE, 'Düşük puan eşiği' DESCRIPTION FROM dual) s
ON (t.SETTING_KEY = s.SETTING_KEY)
WHEN NOT MATCHED THEN INSERT (SETTING_KEY, SETTING_VALUE, DESCRIPTION) VALUES (s.SETTING_KEY, s.SETTING_VALUE, s.DESCRIPTION);

MERGE INTO HGB_RETENTION_POLICIES t USING (SELECT 'SURVEY_RESPONSE' DATA_CATEGORY, 365 RETENTION_DAYS, 'ANONYMIZE' ACTION_AFTER_RETENTION FROM dual) s
ON (t.DATA_CATEGORY = s.DATA_CATEGORY)
WHEN NOT MATCHED THEN INSERT (DATA_CATEGORY, RETENTION_DAYS, ACTION_AFTER_RETENTION) VALUES (s.DATA_CATEGORY, s.RETENTION_DAYS, s.ACTION_AFTER_RETENTION);
MERGE INTO HGB_RETENTION_POLICIES t USING (SELECT 'AUDIT_LOG' DATA_CATEGORY, 1825 RETENTION_DAYS, 'DELETE' ACTION_AFTER_RETENTION FROM dual) s
ON (t.DATA_CATEGORY = s.DATA_CATEGORY)
WHEN NOT MATCHED THEN INSERT (DATA_CATEGORY, RETENTION_DAYS, ACTION_AFTER_RETENTION) VALUES (s.DATA_CATEGORY, s.RETENTION_DAYS, s.ACTION_AFTER_RETENTION);

MERGE INTO HGB_THEME_CATEGORIES t USING (SELECT 'WAIT_TIME' THEME_CODE, 'Bekleme Süresi' THEME_NAME FROM dual) s ON (t.THEME_CODE = s.THEME_CODE)
WHEN NOT MATCHED THEN INSERT (THEME_CODE, THEME_NAME) VALUES (s.THEME_CODE, s.THEME_NAME);
MERGE INTO HGB_THEME_CATEGORIES t USING (SELECT 'STAFF_ATTITUDE' THEME_CODE, 'Personel Tutumu' THEME_NAME FROM dual) s ON (t.THEME_CODE = s.THEME_CODE)
WHEN NOT MATCHED THEN INSERT (THEME_CODE, THEME_NAME) VALUES (s.THEME_CODE, s.THEME_NAME);
MERGE INTO HGB_THEME_CATEGORIES t USING (SELECT 'CLEANLINESS' THEME_CODE, 'Temizlik' THEME_NAME FROM dual) s ON (t.THEME_CODE = s.THEME_CODE)
WHEN NOT MATCHED THEN INSERT (THEME_CODE, THEME_NAME) VALUES (s.THEME_CODE, s.THEME_NAME);
MERGE INTO HGB_THEME_CATEGORIES t USING (SELECT 'COMMUNICATION' THEME_CODE, 'İletişim' THEME_NAME FROM dual) s ON (t.THEME_CODE = s.THEME_CODE)
WHEN NOT MATCHED THEN INSERT (THEME_CODE, THEME_NAME) VALUES (s.THEME_CODE, s.THEME_NAME);
MERGE INTO HGB_THEME_CATEGORIES t USING (SELECT 'TECHNICAL' THEME_CODE, 'Teknik' THEME_NAME FROM dual) s ON (t.THEME_CODE = s.THEME_CODE)
WHEN NOT MATCHED THEN INSERT (THEME_CODE, THEME_NAME) VALUES (s.THEME_CODE, s.THEME_NAME);

INSERT INTO HGB_CONSENT_TEXTS (LANGUAGE_CODE, VERSION_NO, BODY, STATUS)
SELECT 'tr', 1, 'KVKK kapsamında geri bildirim verileriniz hizmet kalitesini artırmak amacıyla işlenecektir. Açık rıza vermeden ankete devam edemezsiniz.', 'ACTIVE' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM HGB_CONSENT_TEXTS WHERE LANGUAGE_CODE = 'tr' AND STATUS = 'ACTIVE');
INSERT INTO HGB_CONSENT_TEXTS (LANGUAGE_CODE, VERSION_NO, BODY, STATUS)
SELECT 'en', 1, 'Your feedback data will be processed to improve service quality. You cannot continue without explicit consent.', 'ACTIVE' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM HGB_CONSENT_TEXTS WHERE LANGUAGE_CODE = 'en' AND STATUS = 'ACTIVE');
INSERT INTO HGB_CONSENT_TEXTS (LANGUAGE_CODE, VERSION_NO, BODY, STATUS)
SELECT 'ar', 1, 'سيتم استخدام ملاحظاتكم لتحسين جودة الخدمة. لا يمكن المتابعة دون موافقة صريحة.', 'ACTIVE' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM HGB_CONSENT_TEXTS WHERE LANGUAGE_CODE = 'ar' AND STATUS = 'ACTIVE');

MERGE INTO HGB_SURVEY_TEMPLATES t USING (
    SELECT 'PATIENT_SATISFACTION_DEFAULT' TEMPLATE_CODE, 'Varsayılan Hasta Memnuniyet Anketi' TEMPLATE_NAME, 'NPS/CSAT, beş puanlı ve serbest metinli demo şablonu' DESCRIPTION FROM dual
) s ON (t.TEMPLATE_CODE = s.TEMPLATE_CODE)
WHEN NOT MATCHED THEN INSERT (TEMPLATE_CODE, TEMPLATE_NAME, DESCRIPTION, STATUS)
VALUES (s.TEMPLATE_CODE, s.TEMPLATE_NAME, s.DESCRIPTION, 'ACTIVE');

INSERT INTO HGB_SURVEY_TEMPLATE_VERSIONS (SURVEY_TEMPLATE_ID, VERSION_NO, VERSION_LABEL, STATUS, PUBLISHED_AT)
SELECT SURVEY_TEMPLATE_ID, 1, 'v1.0', 'PUBLISHED', SYSTIMESTAMP
FROM HGB_SURVEY_TEMPLATES st
WHERE st.TEMPLATE_CODE = 'PATIENT_SATISFACTION_DEFAULT'
  AND NOT EXISTS (SELECT 1 FROM HGB_SURVEY_TEMPLATE_VERSIONS v WHERE v.SURVEY_TEMPLATE_ID = st.SURVEY_TEMPLATE_ID);

INSERT INTO HGB_SURVEY_QUESTIONS (TEMPLATE_VERSION_ID, QUESTION_CODE, QUESTION_ORDER, QUESTION_TYPE, METRIC_TYPE, QUESTION_TEXT_TR, QUESTION_TEXT_EN, QUESTION_TEXT_AR, IS_REQUIRED, IS_INITIAL_QUESTION, MIN_VALUE, MAX_VALUE)
SELECT v.TEMPLATE_VERSION_ID, 'Q_OVERALL', 1, 'SMILEY', 'CSAT', 'Aldığınız hizmetten ne kadar memnun kaldınız?', 'How satisfied are you with the service?', 'ما مدى رضاك عن الخدمة؟', 1, 1, 1, 5
FROM HGB_SURVEY_TEMPLATE_VERSIONS v JOIN HGB_SURVEY_TEMPLATES st ON v.SURVEY_TEMPLATE_ID = st.SURVEY_TEMPLATE_ID
WHERE st.TEMPLATE_CODE = 'PATIENT_SATISFACTION_DEFAULT'
  AND NOT EXISTS (SELECT 1 FROM HGB_SURVEY_QUESTIONS q WHERE q.TEMPLATE_VERSION_ID = v.TEMPLATE_VERSION_ID AND q.QUESTION_CODE = 'Q_OVERALL');

INSERT INTO HGB_SURVEY_QUESTIONS (TEMPLATE_VERSION_ID, QUESTION_CODE, QUESTION_ORDER, QUESTION_TYPE, METRIC_TYPE, QUESTION_TEXT_TR, QUESTION_TEXT_EN, QUESTION_TEXT_AR, IS_REQUIRED, IS_INITIAL_QUESTION, MIN_VALUE, MAX_VALUE)
SELECT v.TEMPLATE_VERSION_ID, 'Q_NPS', 2, 'NPS', 'NPS', 'Bu hastaneyi yakınlarınıza tavsiye eder misiniz?', 'Would you recommend this hospital?', 'هل توصي بهذا المستشفى؟', 0, 0, 0, 10
FROM HGB_SURVEY_TEMPLATE_VERSIONS v JOIN HGB_SURVEY_TEMPLATES st ON v.SURVEY_TEMPLATE_ID = st.SURVEY_TEMPLATE_ID
WHERE st.TEMPLATE_CODE = 'PATIENT_SATISFACTION_DEFAULT'
  AND NOT EXISTS (SELECT 1 FROM HGB_SURVEY_QUESTIONS q WHERE q.TEMPLATE_VERSION_ID = v.TEMPLATE_VERSION_ID AND q.QUESTION_CODE = 'Q_NPS');

INSERT INTO HGB_SURVEY_QUESTIONS (TEMPLATE_VERSION_ID, QUESTION_CODE, QUESTION_ORDER, QUESTION_TYPE, QUESTION_TEXT_TR, QUESTION_TEXT_EN, QUESTION_TEXT_AR, IS_REQUIRED, IS_INITIAL_QUESTION)
SELECT v.TEMPLATE_VERSION_ID, 'Q_NEG_DETAIL', 3, 'FREE_TEXT', 'Deneyiminizde iyileştirmemizi istediğiniz konu nedir?', 'What should we improve?', 'ما الذي يمكننا تحسينه؟', 0, 0
FROM HGB_SURVEY_TEMPLATE_VERSIONS v JOIN HGB_SURVEY_TEMPLATES st ON v.SURVEY_TEMPLATE_ID = st.SURVEY_TEMPLATE_ID
WHERE st.TEMPLATE_CODE = 'PATIENT_SATISFACTION_DEFAULT'
  AND NOT EXISTS (SELECT 1 FROM HGB_SURVEY_QUESTIONS q WHERE q.TEMPLATE_VERSION_ID = v.TEMPLATE_VERSION_ID AND q.QUESTION_CODE = 'Q_NEG_DETAIL');

INSERT INTO HGB_BRANCHING_RULES (SOURCE_QUESTION_ID, OPERATOR_CODE, COMPARE_NUMERIC_VALUE, TARGET_QUESTION_ID, RULE_ORDER)
SELECT q1.QUESTION_ID, 'LTE', 2, q2.QUESTION_ID, 1
FROM HGB_SURVEY_QUESTIONS q1
JOIN HGB_SURVEY_QUESTIONS q2 ON q1.TEMPLATE_VERSION_ID = q2.TEMPLATE_VERSION_ID
WHERE q1.QUESTION_CODE = 'Q_OVERALL' AND q2.QUESTION_CODE = 'Q_NEG_DETAIL'
  AND NOT EXISTS (SELECT 1 FROM HGB_BRANCHING_RULES b WHERE b.SOURCE_QUESTION_ID = q1.QUESTION_ID AND b.TARGET_QUESTION_ID = q2.QUESTION_ID);

MERGE INTO HGB_TRIGGER_RULES t USING (
    SELECT 'DISCHARGE' EVENT_TYPE,
           (SELECT SURVEY_TEMPLATE_ID FROM HGB_SURVEY_TEMPLATES WHERE TEMPLATE_CODE = 'PATIENT_SATISFACTION_DEFAULT') SURVEY_TEMPLATE_ID,
           (SELECT CHANNEL_ID FROM HGB_CHANNELS WHERE CHANNEL_CODE = 'SMS') SMS_ID,
           (SELECT CHANNEL_ID FROM HGB_CHANNELS WHERE CHANNEL_CODE = 'WHATSAPP') WA_ID
    FROM dual
) s ON (t.EVENT_TYPE = s.EVENT_TYPE)
WHEN NOT MATCHED THEN INSERT (EVENT_TYPE, SURVEY_TEMPLATE_ID, PRIMARY_CHANNEL_ID, FALLBACK_CHANNEL_ID, DELAY_MINUTES, LOW_SCORE_THRESHOLD, FREQUENCY_CAP_DAYS, FREQUENCY_CAP_COUNT, REMINDER_ENABLED, REMINDER_COUNT, REMINDER_INTERVAL_MINUTES, SERVICE_RECOVERY_SLA_HOURS)
VALUES (s.EVENT_TYPE, s.SURVEY_TEMPLATE_ID, s.SMS_ID, s.WA_ID, 0, 2, 7, 1, 1, 1, 1440, 24);

MERGE INTO HGB_TRIGGER_RULES t USING (
    SELECT 'OUTPATIENT_COMPLETED' EVENT_TYPE,
           (SELECT SURVEY_TEMPLATE_ID FROM HGB_SURVEY_TEMPLATES WHERE TEMPLATE_CODE = 'PATIENT_SATISFACTION_DEFAULT') SURVEY_TEMPLATE_ID,
           (SELECT CHANNEL_ID FROM HGB_CHANNELS WHERE CHANNEL_CODE = 'SMS') SMS_ID,
           (SELECT CHANNEL_ID FROM HGB_CHANNELS WHERE CHANNEL_CODE = 'WHATSAPP') WA_ID
    FROM dual
) s ON (t.EVENT_TYPE = s.EVENT_TYPE)
WHEN NOT MATCHED THEN INSERT (EVENT_TYPE, SURVEY_TEMPLATE_ID, PRIMARY_CHANNEL_ID, FALLBACK_CHANNEL_ID, DELAY_MINUTES, LOW_SCORE_THRESHOLD, FREQUENCY_CAP_DAYS, FREQUENCY_CAP_COUNT, REMINDER_ENABLED, REMINDER_COUNT, REMINDER_INTERVAL_MINUTES, SERVICE_RECOVERY_SLA_HOURS)
VALUES (s.EVENT_TYPE, s.SURVEY_TEMPLATE_ID, s.SMS_ID, s.WA_ID, 0, 2, 7, 1, 1, 1, 1440, 24);

MERGE INTO HGB_KPI_TARGETS t USING (SELECT 'NPS' KPI_CODE, 50 TARGET_VALUE FROM dual) s
ON (t.KPI_CODE = s.KPI_CODE AND t.DEPARTMENT_ID IS NULL)
WHEN NOT MATCHED THEN INSERT (KPI_CODE, TARGET_PERIOD, TARGET_VALUE, VALID_FROM) VALUES (s.KPI_CODE, 'MONTH', s.TARGET_VALUE, SYSDATE - 1);
MERGE INTO HGB_KPI_TARGETS t USING (SELECT 'CSAT' KPI_CODE, 4 TARGET_VALUE FROM dual) s
ON (t.KPI_CODE = s.KPI_CODE AND t.DEPARTMENT_ID IS NULL)
WHEN NOT MATCHED THEN INSERT (KPI_CODE, TARGET_PERIOD, TARGET_VALUE, VALID_FROM) VALUES (s.KPI_CODE, 'MONTH', s.TARGET_VALUE, SYSDATE - 1);
MERGE INTO HGB_KPI_TARGETS t USING (SELECT 'RESPONSE_RATE' KPI_CODE, 25 TARGET_VALUE FROM dual) s
ON (t.KPI_CODE = s.KPI_CODE AND t.DEPARTMENT_ID IS NULL)
WHEN NOT MATCHED THEN INSERT (KPI_CODE, TARGET_PERIOD, TARGET_VALUE, VALID_FROM) VALUES (s.KPI_CODE, 'MONTH', s.TARGET_VALUE, SYSDATE - 1);

MERGE INTO HGB_SCHEMA_VERSION t
USING (
    SELECT
        '2026-07-base-schema' VERSION_CODE,
        'Base schema, views, indexes and reference data' DESCRIPTION
    FROM dual
) s ON (t.VERSION_CODE = s.VERSION_CODE)
WHEN NOT MATCHED THEN INSERT (VERSION_CODE, DESCRIPTION)
VALUES (s.VERSION_CODE, s.DESCRIPTION);

COMMIT;

PROMPT HGB Oracle temel şema ve referans veri kurulumu tamamlandı.
