-- Idempotent Oracle script. Run after hgb-oracle-install.sql and before starting Production.

WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

SET DEFINE OFF;
SET SERVEROUTPUT ON;
SET VERIFY OFF;

DECLARE
    PROCEDURE create_table_if_missing(p_table_name VARCHAR2, p_sql CLOB) IS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = UPPER(p_table_name);
        IF v_count = 0 THEN
            EXECUTE IMMEDIATE p_sql;
        END IF;
    END;

    PROCEDURE add_column_if_missing(p_table_name VARCHAR2, p_column_name VARCHAR2, p_sql VARCHAR2) IS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_count
        FROM USER_TAB_COLUMNS
        WHERE TABLE_NAME = UPPER(p_table_name)
          AND COLUMN_NAME = UPPER(p_column_name);

        IF v_count = 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE ' || p_table_name || ' ADD (' || p_sql || ')';
        END IF;
    END;

    PROCEDURE create_index_if_missing(p_index_name VARCHAR2, p_sql VARCHAR2) IS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = UPPER(p_index_name);
        IF v_count = 0 THEN
            EXECUTE IMMEDIATE p_sql;
        END IF;
    END;
BEGIN
    create_table_if_missing('HGB_SCHEMA_VERSION', q'[
        CREATE TABLE HGB_SCHEMA_VERSION (
            VERSION_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            VERSION_CODE VARCHAR2(80) UNIQUE NOT NULL,
            DESCRIPTION NVARCHAR2(500),
            APPLIED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
        )]');

    create_table_if_missing('HGB_USER_SCOPES', q'[
        CREATE TABLE HGB_USER_SCOPES (
            USER_SCOPE_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            USER_ID NUMBER NOT NULL,
            SCOPE_TYPE VARCHAR2(30) NOT NULL,
            SCOPE_ID NUMBER NOT NULL,
            IS_ACTIVE NUMBER(1) DEFAULT 1,
            CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
        )]');

    create_table_if_missing('HGB_WEBHOOK_REPLAY', q'[
        CREATE TABLE HGB_WEBHOOK_REPLAY (
            WEBHOOK_REPLAY_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            SIGNATURE_HASH VARCHAR2(128) NOT NULL,
            SOURCE_SYSTEM VARCHAR2(80) NOT NULL,
            RECEIVED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
            EXPIRES_AT TIMESTAMP NOT NULL
        )]');

    add_column_if_missing('HGB_INTEGRATION_LOGS', 'CORRELATION_ID', 'CORRELATION_ID VARCHAR2(80)');
    add_column_if_missing('HGB_INTEGRATION_LOGS', 'PROVIDER_MESSAGE_ID', 'PROVIDER_MESSAGE_ID VARCHAR2(200)');
    add_column_if_missing('HGB_INTEGRATION_LOGS', 'RETRY_COUNT', 'RETRY_COUNT NUMBER DEFAULT 0');
    add_column_if_missing('HGB_INTEGRATION_LOGS', 'NEXT_RETRY_AT', 'NEXT_RETRY_AT TIMESTAMP');

    add_column_if_missing('HGB_AUDIT_LOGS', 'CHANGE_DESCRIPTION', 'CHANGE_DESCRIPTION NVARCHAR2(1000)');
    add_column_if_missing('HGB_WEBHOOK_REPLAY', 'EXPIRES_AT', 'EXPIRES_AT TIMESTAMP');

    add_column_if_missing('HGB_BI_EXPORT_QUEUE', 'RETRY_COUNT', 'RETRY_COUNT NUMBER DEFAULT 0');
    add_column_if_missing('HGB_BI_EXPORT_QUEUE', 'NEXT_RETRY_AT', 'NEXT_RETRY_AT TIMESTAMP');
    add_column_if_missing('HGB_BI_EXPORT_QUEUE', 'LAST_ERROR_MESSAGE', 'LAST_ERROR_MESSAGE NVARCHAR2(1000)');

    create_index_if_missing(
        'UX_HGB_USER_SCOPES_ACTIVE',
        'CREATE UNIQUE INDEX UX_HGB_USER_SCOPES_ACTIVE ON HGB_USER_SCOPES (USER_ID, SCOPE_TYPE, SCOPE_ID, IS_ACTIVE)');

    create_index_if_missing(
        'UX_HGB_WEBHOOK_REPLAY',
        'CREATE UNIQUE INDEX UX_HGB_WEBHOOK_REPLAY ON HGB_WEBHOOK_REPLAY (SIGNATURE_HASH, SOURCE_SYSTEM)');

    create_index_if_missing(
        'IX_HGB_WEBHOOK_REPLAY_AT',
        'CREATE INDEX IX_HGB_WEBHOOK_REPLAY_AT ON HGB_WEBHOOK_REPLAY (RECEIVED_AT)');

    create_index_if_missing(
        'UX_HGB_CLINICAL_EVENT_EXT',
        'CREATE UNIQUE INDEX UX_HGB_CLINICAL_EVENT_EXT ON HGB_CLINICAL_EVENTS (SOURCE_SYSTEM, EXTERNAL_EVENT_REF)');

    create_index_if_missing(
        'IX_HGB_USER_SCOPES_USER',
        'CREATE INDEX IX_HGB_USER_SCOPES_USER ON HGB_USER_SCOPES (USER_ID, IS_ACTIVE)');

    create_index_if_missing(
        'IX_HGB_BI_EXPORT_RETRY',
        'CREATE INDEX IX_HGB_BI_EXPORT_RETRY ON HGB_BI_EXPORT_QUEUE (EXPORT_STATUS, NEXT_RETRY_AT)');
END;
/

UPDATE HGB_WEBHOOK_REPLAY
SET EXPIRES_AT = RECEIVED_AT + NUMTODSINTERVAL(10, 'MINUTE')
WHERE EXPIRES_AT IS NULL;

MERGE INTO HGB_SCHEMA_VERSION t
USING (
    SELECT
        '2026-07-production-hardening' VERSION_CODE,
        'Production security, scope, replay and BI retry metadata' DESCRIPTION
    FROM dual
) s
ON (t.VERSION_CODE = s.VERSION_CODE)
WHEN NOT MATCHED THEN
    INSERT (VERSION_CODE, DESCRIPTION) VALUES (s.VERSION_CODE, s.DESCRIPTION);

MERGE INTO HGB_INTEGRATION_SYSTEMS t
USING (SELECT 'PROBEL_BI' SYSTEM_CODE, 'Probel BI' SYSTEM_NAME, 'BEARER' AUTH_TYPE FROM dual) s
ON (t.SYSTEM_CODE = s.SYSTEM_CODE)
WHEN MATCHED THEN UPDATE SET t.AUTH_TYPE = s.AUTH_TYPE
WHEN NOT MATCHED THEN INSERT (SYSTEM_CODE, SYSTEM_NAME, AUTH_TYPE)
VALUES (s.SYSTEM_CODE, s.SYSTEM_NAME, s.AUTH_TYPE);

COMMIT;
