-- Local mock/demo data only. Do not run in Production.

WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

SET DEFINE OFF;
SET VERIFY OFF;

INSERT INTO HGB_USERS (USERNAME, PASSWORD_HASH, FULL_NAME, EMAIL, PRIMARY_ROLE_ID, STATUS)
SELECT 'admin.demo', '$2a$11$rwQnvvtVwg3tF6REpoGD9uwNe.QTF2j6qP5/fukMgRXIDFHOTMBtu',
       'Demo Yönetici', 'admin.demo@example.com',
       (SELECT ROLE_ID FROM HGB_ROLES WHERE ROLE_CODE = 'SYS_ADMIN'), 'ACTIVE'
FROM dual
WHERE NOT EXISTS (SELECT 1 FROM HGB_USERS WHERE USERNAME = 'admin.demo');

INSERT INTO HGB_USERS (USERNAME, PASSWORD_HASH, FULL_NAME, EMAIL, PRIMARY_ROLE_ID, STATUS)
SELECT 'kalite.demo', '$2a$11$w2uYtUl/J80HBPkBZWWikujaV/KhB2sqKk90CfQotBTlrdtY2LZ46',
       'Demo Kalite Yöneticisi', 'kalite.demo@example.com',
       (SELECT ROLE_ID FROM HGB_ROLES WHERE ROLE_CODE = 'QUALITY_MANAGER'), 'ACTIVE'
FROM dual
WHERE NOT EXISTS (SELECT 1 FROM HGB_USERS WHERE USERNAME = 'kalite.demo');

INSERT INTO HGB_USERS (USERNAME, PASSWORD_HASH, FULL_NAME, EMAIL, PRIMARY_ROLE_ID, STATUS)
SELECT 'birim.demo', '$2a$11$LBjGvS2uJwr8Fs2uWkfyluLcyCZMzON857DN2q8zUMpxdu60WCOD2',
       'Demo Birim Sorumlusu', 'birim.demo@example.com',
       (SELECT ROLE_ID FROM HGB_ROLES WHERE ROLE_CODE = 'UNIT_MANAGER'), 'ACTIVE'
FROM dual
WHERE NOT EXISTS (SELECT 1 FROM HGB_USERS WHERE USERNAME = 'birim.demo');

UPDATE HGB_USERS SET PASSWORD_HASH = '$2a$11$rwQnvvtVwg3tF6REpoGD9uwNe.QTF2j6qP5/fukMgRXIDFHOTMBtu' WHERE USERNAME = 'admin.demo';
UPDATE HGB_USERS SET PASSWORD_HASH = '$2a$11$w2uYtUl/J80HBPkBZWWikujaV/KhB2sqKk90CfQotBTlrdtY2LZ46' WHERE USERNAME = 'kalite.demo';
UPDATE HGB_USERS SET PASSWORD_HASH = '$2a$11$LBjGvS2uJwr8Fs2uWkfyluLcyCZMzON857DN2q8zUMpxdu60WCOD2' WHERE USERNAME = 'birim.demo';

INSERT INTO HGB_USER_ROLES (USER_ID, ROLE_ID)
SELECT u.USER_ID, u.PRIMARY_ROLE_ID
FROM HGB_USERS u
WHERE u.USERNAME IN ('admin.demo', 'kalite.demo', 'birim.demo')
  AND NOT EXISTS (
      SELECT 1 FROM HGB_USER_ROLES ur
      WHERE ur.USER_ID = u.USER_ID AND ur.ROLE_ID = u.PRIMARY_ROLE_ID
  );

MERGE INTO HGB_PATIENTS t USING (
    SELECT 'P-DEMO-001' EXTERNAL_PATIENT_REF, 'Demo Hasta' FULL_NAME, '+905551112233' PHONE, 'tr' PREFERRED_LANGUAGE FROM dual
) s ON (t.EXTERNAL_PATIENT_REF = s.EXTERNAL_PATIENT_REF)
WHEN NOT MATCHED THEN INSERT (EXTERNAL_PATIENT_REF, FULL_NAME, PHONE, PREFERRED_LANGUAGE, ALLOW_CONTACT, IS_DELETED)
VALUES (s.EXTERNAL_PATIENT_REF, s.FULL_NAME, s.PHONE, s.PREFERRED_LANGUAGE, 1, 0);

COMMIT;

SELECT USERNAME, PRIMARY_ROLE_ID, LENGTH(PASSWORD_HASH) AS HASH_LEN
FROM HGB_USERS WHERE USERNAME IN ('admin.demo', 'kalite.demo', 'birim.demo');
